import React,{useRef,useState} from 'react';
import {View,Pressable,Switch} from 'react-native';
import {BANK_SENDER,BANK_DEPARTMENTS,TRIAL_DAYS,OFFER_DAYS,DOCUMENT_DAYS,messageDate} from './BankMessages';
import {PERSONAL_TIERS,MAX_TIER,tierLabel} from './Membership';
import {act,makeId} from './engine';

export default function AdminMessages({u,data,ui,dispatch}){
 const {t,Panel,Label,Button,Row,Field,Chips,Section,Icon}=ui;
 const [tab,T]=useState('Nová zpráva'),[target,V]=useState(u.id),[picker,P]=useState(false),[department,D]=useState(BANK_DEPARTMENTS[0]);
 const [title,H]=useState(''),[body,B]=useState(''),[priority,Q]=useState('Běžná');
 const [offer,O]=useState(false),[tier,Plan]=useState(MAX_TIER),[days,Days]=useState(14),[valid,Valid]=useState(30);
 const [docs,Docs]=useState([]),[review,R]=useState(null),[error,Error]=useState(''),[sent,Sent]=useState(false),[historyId,History]=useState(null);
 const op=useRef(makeId()),sending=useRef(false),recipient=data.users.find(x=>x.id===target);
 if(data.mode!=='Administrátor')return <Panel><Label>Bankovní komunikace vyžaduje režim Administrátor.</Label></Panel>;
 const patchDoc=(id,key,value)=>Docs(items=>items.map(x=>x.id===id?{...x,[key]:value}:x));
 const payload=()=>({type:'bankMessage',target,title,body,department,priority:priority==='Důležitá'?'important':'normal',documents:docs,offer:offer?{tier,days,validDays:valid}:null,op:op.current});
 const prepare=()=>{try{const a=payload();act(data,u.id,a);Error('');R(a);ui.scrollTop?.();}catch(e){Error(e.message);}};
 const send=()=>{if(sending.current)return;sending.current=true;if(dispatch(review,'Zpráva doručena klientovi.')){R(null);Sent(true);}else sending.current=false;};
 const reset=()=>{H('');B('');O(false);Docs([]);R(null);Sent(false);Error('');sending.current=false;op.current=makeId();};
 const attachmentPreview=a=><>
  {a.offer&&<Panel style={{marginTop:14}}><Label style={{color:t.accent,fontWeight:'800',fontSize:12}}>FREE TRIAL · {a.offer.days} DNÍ</Label><Label style={{fontSize:22,fontWeight:'800',marginTop:8}}>{tierLabel(a.offer.tier)} · 0 Kč</Label><Label muted style={{lineHeight:21,fontSize:12,marginTop:8}}>Aktivace do {a.offer.validDays} dní od doručení. Potom návrat na původní plán, bez automatického prodloužení. Bez uvítacích bodů; Art Editions se hradí samostatně.</Label></Panel>}
  {a.documents?.map(x=><Panel key={x.id} style={{marginTop:14}}><Label style={{fontWeight:'700',fontSize:17}}>{x.title}</Label><Label selectable style={{lineHeight:23,marginTop:12}}>{x.body}</Label><Label muted style={{fontSize:11,lineHeight:19,marginTop:12}}>{x.requiresConfirmation?'Vyžaduje potvrzení přečtení':'Pouze pro informaci'} · {x.validDays?'Platnost '+x.validDays+' dní':'Bez omezení platnosti'}</Label></Panel>)}
 </>;
 if(sent)return <Panel><Icon name="checkmark-circle-outline" color={t.accent} size={42}/><Label style={{fontSize:26,fontWeight:'800',marginTop:16}}>Doručeno.</Label><Label muted style={{lineHeight:23,marginVertical:16}}>{recipient?.name} najde zprávu v Oznámení po přihlášení do svého místního účtu.</Label><Button title="Napsat další zprávu" onPress={reset}/><Button title="Zobrazit odeslané" secondary style={{marginTop:10}} onPress={()=>{reset();T('Odeslané');}}/></Panel>;
 if(review)return <View testID="bank-message-review"><Label style={{fontSize:25,fontWeight:'800',marginBottom:17}}>Připraveno k doručení.</Label><Panel><Row icon="person-outline" title={recipient?.name} sub={recipient?.auth?.email||'Místní účet · '+target.slice(-6)}/><Label muted style={{fontSize:12,lineHeight:20,marginTop:12}}>Od {BANK_SENDER} · {review.department}</Label><Label style={{fontSize:23,fontWeight:'800',marginTop:18}}>{review.title}</Label><Label selectable style={{lineHeight:24,marginTop:15}}>{review.body}</Label></Panel>{attachmentPreview(review)}<Label muted style={{fontSize:12,lineHeight:20,marginVertical:18}}>Doručí se pouze vybranému místnímu účtu. Odeslanou zprávu a přílohy již nelze změnit.</Label><Button title="Odeslat klientovi" icon="send-outline" onPress={send}/><Button title="Upravit zprávu" secondary style={{marginTop:10}} onPress={()=>R(null)}/></View>;
 const history=(data.bankOutbox||[]).map(x=>({...x,m:data.users.find(u=>u.id===x.recipientId)?.bankMessages.find(m=>m.id===x.id)}));
 const entry=history.find(x=>x.id===historyId);
 return <View testID="bank-message-admin">
  <Label style={{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:t.accent,marginBottom:10}}>ADMIN TOOLS · KOMUNIKACE</Label><Label muted style={{lineHeight:22,marginBottom:15}}>Zprávy jménem {BANK_SENDER}. Doručení do schránky zvoleného místního klienta, bez e-mailu nebo push notifikací.</Label>
  <Chips items={['Nová zpráva','Odeslané']} value={tab} onChange={v=>{T(v);History(null);}}/>
  {tab==='Odeslané'?(entry?<><Button title="Zpět na odeslané" secondary style={{marginTop:14}} onPress={()=>History(null)}/><Panel style={{marginTop:16}}><Label muted style={{fontSize:12}}>{entry.recipientName} · {messageDate(entry.date)}</Label><Label style={{fontSize:23,fontWeight:'800',marginTop:14}}>{entry.title}</Label><Label style={{lineHeight:24,marginTop:15}}>{entry.m?.body||'Účet příjemce již není dostupný.'}</Label><Label muted style={{fontSize:12,lineHeight:21,marginTop:16}}>{entry.m?.readAt?'Přečteno '+messageDate(entry.m.readAt):'Zatím nepřečteno'}{entry.m?.offer?.redeemedAt?'\nTrial aktivován '+messageDate(entry.m.offer.redeemedAt):''}</Label></Panel>{entry.m?.offer&&<Panel style={{marginTop:12}}><Label style={{fontWeight:'700'}}>Free trial {entry.m.offer.tier} · {entry.m.offer.days} dní</Label><Label muted style={{lineHeight:21,marginTop:7}}>Aktivace do {messageDate(entry.m.offer.expiresAt)}</Label></Panel>}{entry.m?.documents.map(x=><Panel key={x.id} style={{marginTop:12}}><Label style={{fontWeight:'700'}}>{x.title}</Label><Label style={{lineHeight:23,marginTop:10}}>{x.body}</Label><Label muted style={{fontSize:12,lineHeight:20,marginTop:10}}>{x.confirmedAt?'Potvrzeno '+x.confirmedBy+' · '+messageDate(x.confirmedAt):x.requiresConfirmation?'Čeká na potvrzení':'Pro informaci'}</Label></Panel>)}</>:<Panel style={{marginTop:15}}>{history.length?history.map(x=><Row key={x.id} icon="paper-plane-outline" title={x.title} sub={x.recipientName+' · '+(x.m?.readAt?'Přečteno':'Doručeno')} onPress={()=>{History(x.id);ui.scrollTop?.();}}/>):<Label muted>Zatím nejsou odeslané zprávy.</Label>}</Panel>):<>
   <Section title="Příjemce"/><Panel><Row icon="person-circle-outline" title={recipient?.name||'Vyber klienta'} sub={(recipient?.tier||'')+' · '+(recipient?.auth?.email||'Místní účet')} onPress={()=>P(!picker)}/>{picker&&data.users.map(x=><Pressable key={x.id} accessibilityRole="button" accessibilityLabel={'Příjemce '+x.name} accessibilityState={{selected:x.id===target}} onPress={()=>{V(x.id);P(false);Error('');}} style={{paddingVertical:14,borderTopWidth:1,borderColor:t.border}}><Label style={{fontWeight:'700'}}>{x.name}{x.id===target?' ✓':''}</Label><Label muted style={{fontSize:12,marginTop:4}}>{x.tier} · {x.auth?.email||x.id.slice(-6)}</Label></Pressable>)}</Panel>
   <Section title="Zpráva od banky"/><Chips items={BANK_DEPARTMENTS} value={department} onChange={D}/><Chips items={['Běžná','Důležitá']} value={priority} onChange={Q}/>
   <View style={{marginTop:16}}><Field label="Předmět zprávy" value={title} onChangeText={H} maxLength={120} placeholder="Máme pro tebe něco navíc"/><Field label="Text zprávy" value={body} onChangeText={B} multiline numberOfLines={5} maxLength={6000} placeholder="Napiš osobní zprávu klientovi…"/></View>
   <Panel><Row icon="gift-outline" title="Přiložit Free trial" sub="Bezplatné zkušební období vybraného plánu" right={<Switch accessibilityLabel="Přiložit Free trial" value={offer} onValueChange={O} trackColor={{true:t.button}}/>}/>{offer&&<><Label muted style={{fontSize:12,marginTop:14}}>Plán</Label><Chips items={PERSONAL_TIERS.filter(x=>x!=='Silver')} value={tier} onChange={Plan}/><Label muted style={{fontSize:12,marginTop:13}}>Délka zkušebního období</Label><Chips items={TRIAL_DAYS.map(x=>x+' dní zdarma')} value={days+' dní zdarma'} onChange={v=>Days(parseInt(v))}/><Label muted style={{fontSize:12,marginTop:13}}>Nabídka platí od doručení</Label><Chips items={OFFER_DAYS.map(x=>x+' dní')} value={valid+' dní'} onChange={v=>Valid(parseInt(v))}/><Label muted style={{fontSize:12,lineHeight:20,marginTop:10}}>Trial lze aktivovat jednou na vyšší osobní plán. Respektuje závazek Core a nekombinuje se s jiným trialem.</Label></>}</Panel>
   <Section title={'Dokumenty · '+docs.length+'/3'}/>{docs.map((x,i)=><Panel key={x.id} style={{marginBottom:14}}><Field label={'Název dokumentu '+(i+1)} value={x.title} onChangeText={v=>patchDoc(x.id,'title',v)} maxLength={120}/><Field label={'Text dokumentu '+(i+1)} value={x.body} onChangeText={v=>patchDoc(x.id,'body',v)} multiline numberOfLines={6} maxLength={12000}/><Row title="Potvrzení přečtení" right={<Switch accessibilityLabel={'Vyžadovat potvrzení dokumentu '+(i+1)} value={x.requiresConfirmation} onValueChange={v=>patchDoc(x.id,'requiresConfirmation',v)} trackColor={{true:t.button}}/>}/><Chips items={DOCUMENT_DAYS.map(x=>x?x+' dní':'Bez expirace')} value={x.validDays?x.validDays+' dní':'Bez expirace'} onChange={v=>patchDoc(x.id,'validDays',parseInt(v)||0)}/><Button title={'Odebrat dokument '+(i+1)} secondary onPress={()=>Docs(items=>items.filter(d=>d.id!==x.id))}/></Panel>)}
   <Button title="Přidat textový dokument" secondary icon="document-attach-outline" disabled={docs.length>=3} onPress={()=>Docs(items=>[...items,{id:makeId(),title:'',body:'',requiresConfirmation:true,validDays:30}])}/>
   {!!error&&<Label accessibilityRole="alert" style={{color:t.accent,lineHeight:22,marginTop:18}}>{error}</Label>}
   <Button title="Náhled zprávy" icon="eye-outline" style={{marginTop:22}} onPress={prepare}/>
  </>}
 </View>;
}
