import {createAuthTask} from './AuthTask';
import LocalAccountImport from './LocalAccountImport';
import React,{useState,useRef,useEffect} from 'react';
import {View,Text,ScrollView,TextInput,Pressable,Modal,StyleSheet,KeyboardAvoidingView,Platform,ActivityIndicator,StatusBar,BackHandler} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {Ionicons} from '@expo/vector-icons';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Enter,Touch,useReducedMotion} from './Motion';
import {identityOf,validateRegistration} from './AuthModel';
import {tierLabel,coreOfferAvailable} from './Membership';
import {CoreBadges,CoreTermPicker,CoreConsent,corePriceText} from './CorePlan';
import {cardArtwork} from './CardArtwork';
import UnlimitedCard from './UnlimitedCard';

const ink='#132439',muted='#5C7188',blue='#147BE5';
const steps=['Přístup','O tobě','Adresa','Finance','Daně','Totožnost','Plán','Souhrn'];
const copy=[['Začíná to u tebe.','Vytvoř si přístup, který zůstává na tomto zařízení.'],['Těší nás. Jak se jmenuješ?','Základní údaje pro tvůj osobní profil.'],['Místo, kterému říkáš doma.','Zadej adresu svého trvalého pobytu.'],['Peníze v tvém rytmu.','Pomoz nám sestavit přehled tvých potřeb.'],['Ještě pár důležitých údajů.','Daňová rezidence a osobní prohlášení.'],['Tvoje identita. Tvůj účet.','Připravíme profil pro pozdější ověření.'],['Vyber si svůj Zenvault.','Od chytrého základu až po Prestige MAX.'],['Všechno sedí?','Zkontroluj údaje. Pak už je Zenvault tvůj.']];
function AButton({title,onPress,secondary=false,disabled=false,loading=false}){return <Touch accessibilityRole="button" accessibilityLabel={title} onPress={onPress} disabled={disabled||loading} style={{minHeight:55,borderRadius:21,backgroundColor:secondary?'#E6EFF8':blue,opacity:disabled?.45:1,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:9,paddingHorizontal:18}}>{loading?<ActivityIndicator color="#FFFFFF"/>:null}<Text style={{fontSize:15,fontWeight:'700',color:secondary?ink:'#FFFFFF'}}>{title}</Text>{!secondary&&!loading&&<Ionicons name="arrow-forward" color="#FFFFFF" size={19}/>}</Touch>;}
function Input({label,hint,secure=false,...props}){const [show,S]=useState(false);return <View style={{marginBottom:19}}><Text style={a.label}>{label}</Text><View style={{flexDirection:'row',alignItems:'center',backgroundColor:'#FFFFFFDA',borderWidth:1,borderColor:'#D9E5F1',borderRadius:18}}><TextInput accessibilityLabel={label} placeholderTextColor="#75869B" secureTextEntry={secure&&!show} style={{flex:1,minHeight:55,paddingHorizontal:16,paddingVertical:15,fontSize:16,color:ink}} autoCapitalize="none" autoCorrect={false} maxLength={180} {...props}/>{secure&&<Pressable accessibilityRole="button" accessibilityLabel={show?'Skrýt '+label:'Zobrazit '+label} onPress={()=>S(v=>!v)} style={{padding:14}}><Ionicons name={show?'eye-off-outline':'eye-outline'} size={21} color={muted}/></Pressable>}</View>{hint&&<Text style={a.hint}>{hint}</Text>}</View>;}
function Select({label,value,items,onChange}){const [open,O]=useState(false);return <View style={{marginBottom:19}}><Text style={a.label}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{expanded:open}} onPress={()=>O(!open)} style={[a.select,{backgroundColor:'#FFFFFFDA'}]}><Text style={{color:value?ink:muted,fontSize:15,flex:1}}>{value||'Vyber možnost'}</Text><Ionicons name={open?'chevron-up':'chevron-down'} size={18} color={muted}/></Pressable>{open&&<View style={{marginTop:6,borderRadius:18,borderWidth:1,borderColor:'#D9E5F1',backgroundColor:'#FFFFFF',overflow:'hidden'}}>{items.map(v=><Pressable accessibilityRole="button" accessibilityLabel={label+': '+v} key={v} onPress={()=>{onChange(v);O(false);}} style={{padding:15,minHeight:48,backgroundColor:value===v?'#ECF6FF':'#FFFFFF'}}><Text style={{color:ink,fontWeight:value===v?'700':'400'}}>{v}{value===v?' ✓':''}</Text></Pressable>)}</View>}</View>;}
function Check({label,value,onChange,sub}){return <Pressable accessibilityRole="checkbox" accessibilityLabel={label} accessibilityState={{checked:!!value}} onPress={()=>onChange(!value)} style={{flexDirection:'row',alignItems:'flex-start',gap:12,paddingVertical:12,minHeight:48}}><View style={{width:23,height:23,borderRadius:8,borderWidth:1.5,borderColor:value?blue:'#A8BBCC',backgroundColor:value?blue:'#FFFFFF',alignItems:'center',justifyContent:'center'}}>{value&&<Ionicons name="checkmark" size={17} color="#FFFFFF"/>}</View><View style={{flex:1}}><Text style={{fontSize:14,fontWeight:'600',lineHeight:21,color:ink}}>{label}</Text>{sub&&<Text style={a.hint}>{sub}</Text>}</View></Pressable>;}
function Note({children}){return <View style={{backgroundColor:'#E7F3FF',padding:17,borderRadius:19,marginVertical:13,borderWidth:1,borderColor:'#D8EBFF'}}><Text style={{fontSize:13,lineHeight:21,color:'#315574'}}>{children}</Text></View>;}
const emptyForm={email:'',phone:'',password:'',confirm:'',firstName:'',lastName:'',birth:'',citizenship:'Česko',street:'',city:'',postcode:'',country:'Česko',occupation:'',income:'',funds:'',purpose:'',taxCountry:'Česko',taxId:'',taxIdPending:true,usTax:'',pep:'',identityMethod:'',identityAck:false,tier:'Silver',coreTerm:'semiannual',coreConsent:false,localConsent:false,accurate:false,marketing:false};

export default function AuthScreen({users,tiers,onQuick,onLogin,onRegister,onImport,initialRoute='welcome',initialAccount}){
 const insets=useSafeAreaInsets(),reduced=useReducedMotion(),scroll=useRef(null),working=useRef(false),operation=useRef(null),alive=useRef(true);
 const [route,R]=useState(initialRoute),[account,A]=useState(initialAccount||users[0]?.id),[dropdown,D]=useState(false),[identifier,I]=useState(identityOf(users.find(x=>x.id===initialAccount)||{})),[password,P]=useState(''),[step,S]=useState(0),[form,F]=useState(emptyForm),[error,E]=useState(''),[busy,B]=useState(false),[info,Q]=useState(null),[progress,G]=useState(0);
 const selected=users.find(x=>x.id===account)||users[0];
 const change=(k,v)=>{F(f=>({...f,[k]:v,...(['tier','coreTerm'].includes(k)?{coreConsent:false}:{})}));E('');};
 const navigate=next=>{if(working.current)return;R(next);E('');D(false);P('');};
 const back=()=>{if(working.current)return;if(route==='register'&&step>0)S(s=>s-1);else navigate('welcome');E('');};
 useEffect(()=>{scroll.current?.scrollTo({y:0,animated:false});},[route,step]);
 useEffect(()=>{if(Platform.OS!=='android')return;const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(route!=='welcome'){back();return true;}return false;});return()=>sub.remove();},[route,step]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;operation.current?.cancel();};},[]);
 const run=async fn=>{if(working.current)return;working.current=true;E('');G(0);B(true);const task=createAuthTask(p=>{if(alive.current)G(Math.min(99,Math.round(p*100)));});operation.current=task;try{await task.wait(Promise.resolve().then(()=>fn(task)));}catch(e){if(alive.current)E(e.message||'Nepodařilo se pokračovat. Zkus to znovu.');}finally{if(operation.current===task){operation.current=null;working.current=false;if(alive.current)B(false);}}};
 const quick=()=>{if(!selected)return;if(selected.auth?.credential){I(identityOf(selected));navigate('login');}else run(()=>onQuick(selected.id));};
 const next=()=>{const err=validateRegistration(step,form,users);if(err){E(err);scroll.current?.scrollToEnd({animated:!reduced});return;}if(step<7){S(s=>s+1);E('');}else run(task=>onRegister({...form},task));};
 const field=(key,label,props={})=><Input key={key} label={label} value={form[key]} onChangeText={v=>change(key,v)} {...props}/>;
 const choose=(key,label,items)=><Select label={label} value={form[key]} items={items} onChange={v=>change(key,v)}/>;
 const heroCard={tier:'Unlimited',type:'Virtuální',network:'Mastercard',last:'0000',builder:{motif:'unlimited-chrome-stars',edge:'hologram',color:'#46B8FF',layout:'full'}};
 return <View testID="auth-screen" style={{flex:1,backgroundColor:'#F2F7FD'}}><StatusBar barStyle="dark-content" backgroundColor="#F2F7FD"/>
  <View pointerEvents="none" style={[StyleSheet.absoluteFillObject,{overflow:'hidden'}]}><LinearGradient colors={['#CAE7FF','#EAF2FF00']} start={{x:.9,y:0}} end={{x:.1,y:1}} style={{position:'absolute',top:0,left:0,right:0,height:580}}/><View style={{position:'absolute',top:120,right:-200,width:480,height:480,borderRadius:240,borderWidth:1,borderColor:'#FFFFFFD0',transform:[{rotate:'-20deg'}]}}/><View style={{position:'absolute',top:180,right:-230,width:490,height:320,borderRadius:240,borderWidth:30,borderColor:'#FFFFFF25',transform:[{rotate:'-30deg'}]}}/></View>
  <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}>
   <ScrollView ref={scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={{paddingTop:insets.top+22,paddingBottom:insets.bottom+26,paddingHorizontal:25,width:'100%',maxWidth:660,alignSelf:'center'}}>
    <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:route==='welcome'?23:28}}><Text style={{fontSize:27,fontWeight:'800',letterSpacing:-1.6,color:ink}}>zenvault®</Text>{route==='welcome'?<View style={{paddingHorizontal:12,paddingVertical:7,borderRadius:20,backgroundColor:'#FFFFFFAA',borderWidth:1,borderColor:'#FFFFFF'}}><Text style={{fontSize:10,fontWeight:'800',letterSpacing:1.3,color:'#467494'}}>NEXT CHAPTER · 4.6.1</Text></View>:<Pressable accessibilityRole="button" accessibilityLabel="Zpět" disabled={busy} onPress={back} style={{height:42,width:42,borderRadius:21,backgroundColor:'#FFFFFFAA',alignItems:'center',justifyContent:'center'}}><Ionicons name="arrow-back" size={21} color={ink}/></Pressable>}</View>
    <Enter key={route}>
     {route==='welcome'?<View testID="welcome-page">
      <Text style={{fontSize:10,fontWeight:'800',letterSpacing:2.3,color:'#407AA9',marginBottom:13}}>BANK & CO. / EST. FOR YOU</Text>
      <Text style={{fontSize:44,fontWeight:'700',letterSpacing:-2.4,lineHeight:48,color:ink}}>Tvoje peníze.{ '\n'}Tvoje pravidla<Text style={{color:blue}}>.</Text></Text>
      <Text style={{fontSize:15,lineHeight:23,color:muted,marginTop:16,maxWidth:310}}>Nový prostor pro všechno, co máš v plánu. Vítej v Zenvault 4.6.1.</Text>
      <View style={{marginTop:26,marginBottom:26,paddingVertical:16,paddingHorizontal:8}}><View style={{position:'absolute',left:24,right:2,top:6,bottom:4,backgroundColor:'#A5CBF0',borderRadius:29,transform:[{rotate:'7deg'}],opacity:.3}}/><View style={{transform:[{rotate:'-4deg'}],shadowColor:'#234E7A',shadowOffset:{width:0,height:15},shadowOpacity:.19,shadowRadius:22}}><UnlimitedCard compact card={heroCard} art={cardArtwork(heroCard)} name="YOUR NEXT CHAPTER" renderNetwork={()=><View style={{flexDirection:'row'}}><View style={{width:23,height:23,borderRadius:12,backgroundColor:'#EB001B'}}/><View style={{width:23,height:23,borderRadius:12,backgroundColor:'#FF9F00',marginLeft:-8,opacity:.94}}/></View>}/></View><View style={{position:'absolute',bottom:0,left:22,paddingHorizontal:15,paddingVertical:11,borderRadius:22,backgroundColor:'#FFFFFFF2',borderWidth:1,borderColor:'#FFFFFF',flexDirection:'row',gap:7,alignItems:'center'}}><Ionicons name="sparkles" color={blue} size={14}/><Text style={{fontSize:10,color:ink,fontWeight:'700'}}>UNLIMITED POSSIBILITIES ∞</Text></View></View>
      <AButton title="Vytvořit účet" onPress={()=>navigate('register')}/><View style={{height:10}}/><AButton title="Přihlásit se" secondary onPress={()=>{I('');navigate('login');}}/>
      <View style={{flexDirection:'row',alignItems:'center',gap:12,marginVertical:23}}><View style={{height:1,backgroundColor:'#D8E3F0',flex:1}}/><Text style={{fontSize:10,fontWeight:'700',letterSpacing:1.3,color:muted}}>NEBO POKRAČUJ TADY</Text><View style={{height:1,backgroundColor:'#D8E3F0',flex:1}}/></View>
      <Pressable accessibilityRole="button" accessibilityLabel="Místní účty" accessibilityState={{expanded:dropdown}} onPress={()=>D(!dropdown)} style={[a.select,{backgroundColor:'#FFFFFFCF',padding:16}]}><View style={{width:39,height:39,borderRadius:14,backgroundColor:'#E2F0FF',alignItems:'center',justifyContent:'center',marginRight:12}}><Ionicons name="person-outline" size={20} color={blue}/></View><View style={{flex:1}}><Text style={{fontSize:13,fontWeight:'700',color:ink}}>{selected?.name||'Vyber místní účet'}</Text><Text style={{fontSize:10,color:muted,marginTop:4}}>{selected?'Zenvault '+tierLabel(selected.tier):'Účty na tomto zařízení'}</Text></View><Ionicons name={dropdown?'chevron-up':'chevron-down'} size={18} color={muted}/></Pressable>
      {dropdown&&<View testID="local-account-dropdown" style={{marginTop:7,padding:5,borderRadius:20,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#D9E5F1'}}>{users.map(x=><Pressable accessibilityRole="button" accessibilityLabel={'Účet '+x.name} key={x.id} onPress={()=>{A(x.id);D(false);}} style={{padding:14,minHeight:54,flexDirection:'row',alignItems:'center',gap:10,borderRadius:15,backgroundColor:x.id===account?'#EDF6FF':'transparent'}}><View style={{flex:1}}><Text style={{fontWeight:'600',color:ink,fontSize:13}}>{x.name}</Text><Text style={{fontSize:10,color:muted,marginTop:4}}>{tierLabel(x.tier)} · {x.auth?'Chráněno heslem':'Místní profil'}</Text></View><Ionicons name={x.auth?'lock-closed-outline':'chevron-forward'} size={16} color={muted}/></Pressable>)}</View>}
      {selected&&<Pressable accessibilityRole="button" accessibilityLabel="Pokračovat s vybraným účtem" disabled={busy} onPress={quick} style={{minHeight:45,alignItems:'center',justifyContent:'center',marginTop:5}}><Text style={{fontWeight:'700',fontSize:12,color:blue}}>{busy?'Otevírám…':'Pokračovat s vybraným účtem →'}</Text></Pressable>}
      <Pressable accessibilityRole="button" accessibilityLabel="Importovat místní účet" disabled={busy} onPress={()=>navigate('import')} style={{padding:17,alignItems:'center'}}><Text style={{fontWeight:'600',fontSize:13,color:blue}}>Importovat místní účet</Text></Pressable>
      <Text style={{fontSize:10,color:muted,textAlign:'center',lineHeight:17,marginTop:8}}>Místní účty se ukládají na tomto zařízení.</Text>
     </View>:route==='import'?<LocalAccountImport busy={busy} onImport={(text,consent)=>run(task=>onImport(text,consent,task))}/>:route==='login'?<View testID="login-page">
      <View style={a.symbol}><Ionicons name="key-outline" size={28} color={blue}/></View><Text style={a.title}>Zase spolu.</Text><Text style={a.subtitle}>Přihlas se do svého prostoru pro peníze.</Text>
      <Input label="E-mail nebo telefonní číslo" value={identifier} onChangeText={I} placeholder="ty@email.cz nebo +420…" textContentType="username" autoComplete="username"/>
      <Input label="Heslo" value={password} onChangeText={P} secure placeholder="Tvoje heslo" maxLength={128} textContentType="password" autoComplete="current-password" onSubmitEditing={()=>run(task=>onLogin(identifier,password,task))}/>
      <Pressable accessibilityRole="button" accessibilityLabel="Zapomenuté heslo" onPress={()=>Q('password')} style={{alignSelf:'flex-end',minHeight:44,justifyContent:'center',marginBottom:15}}><Text style={{fontSize:12,fontWeight:'600',color:blue}}>Zapomenuté heslo?</Text></Pressable>
      <AButton title="Otevřít Zenvault" loading={busy} onPress={()=>run(task=>onLogin(identifier,password,task))}/>
      <Pressable accessibilityRole="button" accessibilityLabel="Nemám účet" onPress={()=>navigate('register')} style={{padding:20,alignItems:'center'}}><Text style={{color:muted,fontSize:13}}>Poprvé tady? <Text style={{fontWeight:'700',color:blue}}>Vytvoř si účet</Text></Text></Pressable>
      <Note>Účty vytvořené dříve bez hesla otevřeš přes seznam místních účtů na úvodní stránce.</Note>
     </View>:<View testID="registration-page">
      <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:10}}><Text style={{color:blue,fontWeight:'800',fontSize:10,letterSpacing:1.3}}>TVŮJ NOVÝ ZAČÁTEK</Text><Text style={{color:muted,fontSize:11}}>{step+1} / 8 · {steps[step]}</Text></View><View style={{height:4,backgroundColor:'#D9E7F4',borderRadius:3,marginBottom:25}}><View style={{width:((step+1)/8*100)+'%',height:4,borderRadius:3,backgroundColor:blue}}/></View>
      <Text style={a.title}>{copy[step][0]}</Text><Text style={a.subtitle}>{copy[step][1]}</Text>
      {step===0&&<>{field('email','E-mail',{keyboardType:'email-address',placeholder:'ty@email.cz',textContentType:'emailAddress',autoComplete:'email',maxLength:254})}{field('phone','Telefonní číslo',{keyboardType:'phone-pad',placeholder:'+420 777 123 456',textContentType:'telephoneNumber',autoComplete:'tel'})}{field('password','Nové heslo',{secure:true,maxLength:128,textContentType:'newPassword',autoComplete:'new-password',hint:'Alespoň 15 znaků. Klidně delší fráze, která dává smysl jen tobě.'})}{field('confirm','Potvrzení hesla',{secure:true,maxLength:128,textContentType:'newPassword'})}<Note>E-mail a telefon slouží k místnímu přihlášení. Ověřovací zprávy se v této verzi neposílají.</Note></>}
      {step===1&&<>{field('firstName','Jméno',{autoCapitalize:'words',textContentType:'givenName'})}{field('lastName','Příjmení',{autoCapitalize:'words',textContentType:'familyName'})}{field('birth','Datum narození',{placeholder:'DD.MM.RRRR',keyboardType:'numbers-and-punctuation',maxLength:10})}{field('citizenship','Státní občanství',{autoCapitalize:'words'})}<Text style={a.hint}>Osobní účet od 18 let. Junior účet může založit rodič ve své aplikaci.</Text></>}
      {step===2&&<>{field('street','Ulice a číslo domu',{textContentType:'streetAddressLine1',autoCapitalize:'words'})}{field('city','Město',{textContentType:'addressCity',autoCapitalize:'words'})}{field('postcode','PSČ',{textContentType:'postalCode',maxLength:12})}{field('country','Země pobytu',{textContentType:'countryName',autoCapitalize:'words'})}</>}
      {step===3&&<>{choose('occupation','Pracovní situace',['Zaměstnanec','Podnikatel / OSVČ','Student','Důchodce','Rodičovská dovolená','Jiné'])}{choose('income','Čistý měsíční příjem',['Do 20 000 Kč','20 000–50 000 Kč','50 000–100 000 Kč','100 000–250 000 Kč','Nad 250 000 Kč'])}{choose('funds','Hlavní původ peněz',['Mzda','Podnikání','Úspory / investice','Důchod / dávky','Rodina / dar / dědictví','Jiné'])}{choose('purpose','Účel účtu',['Každodenní platby','Spoření','Cestování','Příjem a správa financí'])}</>}
      {step===4&&<>{field('taxCountry','Země daňové rezidence',{autoCapitalize:'words'})}<Check label="Daňový identifikátor doplním při ověření" value={form.taxIdPending} onChange={v=>change('taxIdPending',v)}/>{!form.taxIdPending&&field('taxId','Daňový identifikátor (TIN)',{hint:'V této lokální verzi používej testovací údaj.'})}{choose('usTax','Máš daňovou vazbu na USA?',['Ano','Ne'])}{choose('pep','Jsi politicky exponovaná osoba?',['Ano','Ne'])}<Text style={a.hint}>Zahrnuje také rodinné příslušníky nebo blízké spolupracovníky osoby ve významné veřejné funkci. Podrobnosti se upřesní při ověřování.</Text></>}
      {step===5&&<>{['Bank iD','Doklad a selfie'].map((m,i)=><Pressable key={m} accessibilityRole="button" accessibilityLabel={'Ověření '+m} onPress={()=>change('identityMethod',m)} style={{borderRadius:23,padding:20,borderWidth:1.5,borderColor:form.identityMethod===m?blue:'#D9E5F1',backgroundColor:'#FFFFFFCC',marginBottom:12}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Ionicons name={i?'id-card-outline':'shield-checkmark-outline'} size={27} color={blue}/><Ionicons name={form.identityMethod===m?'checkmark-circle':'ellipse-outline'} color={form.identityMethod===m?blue:'#A8BBCC'} size={22}/></View><Text style={{fontSize:19,fontWeight:'700',color:ink,marginTop:14}}>{m}</Text><Text style={a.hint}>{i?'Doklad totožnosti a kontrola živosti.':'Propojení s ověřenou bankovní identitou.'}</Text></Pressable>)}<Note>Vytvoříš místní účet se stavem „Totožnost neověřena“. Bank iD, kontrola dokladu a selfie zatím nejsou připojené. Fotografie dokladů zde neukládáme.</Note><Check label="Ověření totožnosti dokončím později" value={form.identityAck} onChange={v=>change('identityAck',v)}/></>}
      {step===6&&<>{tiers.filter(z=>z.name!=='Business').map(z=><Pressable accessibilityRole="button" accessibilityLabel={'Plán '+tierLabel(z.name)} key={z.name} disabled={z.name==='Core'&&!coreOfferAvailable()} onPress={()=>change('tier',z.name)} style={{padding:21,borderRadius:24,borderWidth:1.5,borderColor:form.tier===z.name?blue:'#D9E5F1',backgroundColor:'#FFFFFFD9',marginBottom:12}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{color:ink,fontSize:21,fontWeight:'700'}}>{tierLabel(z.name)}</Text><Ionicons name={form.tier===z.name?'checkmark-circle':'ellipse-outline'} size={23} color={form.tier===z.name?blue:'#B5C5D6'}/></View>{z.name==='Core'&&<CoreBadges/>}<Text style={{color:blue,fontWeight:'700',fontSize:18,marginTop:9}}>{z.price} Kč<Text style={{fontSize:12,fontWeight:'400',color:muted}}> / měsíc</Text></Text><Text style={{color:muted,fontSize:12,lineHeight:20,marginTop:10}}>{z.tag}</Text>{z.name==='Core'&&<Text style={a.hint}>{coreOfferAvailable()?'Minimálně 6 měsíců · celkem 1 494 Kč. Nebo 2 490 Kč / rok. Sjednání do 1. 1. 2027 včetně.':'Nové sjednání Core již skončilo.'}</Text>}{(z.name==='Core'?z.benefits:z.benefits.slice(-3)).map(b=><Text key={b} style={{color:muted,fontSize:11,lineHeight:19,marginTop:6}}>✓ {b}</Text>)}</Pressable>)}{form.tier==='Core'&&<CoreTermPicker value={form.coreTerm} onChange={v=>change('coreTerm',v)}/>}<Note>Business má cenu na vyžádání a samostatné podmínky. Volba osobního plánu nastaví jeho funkce v aplikaci; žádný poplatek se automaticky nestrhne.</Note></>}
      {step===7&&<><View style={{padding:20,borderRadius:24,backgroundColor:'#FFFFFFCC',borderWidth:1,borderColor:'#D9E5F1'}}>{[['Profil',form.firstName+' '+form.lastName,1],['Kontakt',form.email+'\n'+form.phone,0],['Adresa',form.street+', '+form.city+' '+form.postcode+'\n'+form.country,2],['Finance',form.occupation+' · '+form.income+'\n'+form.funds+' · '+form.purpose,3],['Daňová rezidence',form.taxCountry+' · USA: '+form.usTax+' · PEP: '+form.pep,4],['Totožnost',form.identityMethod+' · čeká na ověření',5],['Plán','Zenvault '+tierLabel(form.tier)+(form.tier==='Core'?' · '+corePriceText(form.coreTerm):''),6]].map(([label,value,index])=><Pressable key={label} accessibilityRole="button" accessibilityLabel={'Upravit '+label} disabled={busy} onPress={()=>S(index)} style={{paddingVertical:12,flexDirection:'row',alignItems:'center',gap:8}}><View style={{flex:1}}><Text style={{fontSize:10,color:muted,marginBottom:5}}>{label}</Text><Text style={{fontSize:13,color:ink,lineHeight:20,fontWeight:'600'}}>{value}</Text></View><Ionicons name="create-outline" size={17} color={blue}/></Pressable>)}</View>{form.tier==='Core'&&<CoreConsent value={form.coreConsent} term={form.coreTerm} onChange={v=>change('coreConsent',v)}/>}<Check label="Potvrzuji správnost zadaných údajů" value={form.accurate} onChange={v=>change('accurate',v)}/><Check label="Souhlasím s podmínkami místního účtu" value={form.localConsent} onChange={v=>change('localConsent',v)} sub="Údaje zůstávají v úložišti aplikace na tomto zařízení. Nevzniká skutečný bankovní účet."/><Pressable accessibilityRole="button" accessibilityLabel="Přečíst podmínky" onPress={()=>Q('terms')} style={{minHeight:40,justifyContent:'center'}}><Text style={{color:blue,fontSize:12,textDecorationLine:'underline'}}>Podmínky a informace o údajích</Text></Pressable><Check label="Chci novinky a nabídky" value={form.marketing} onChange={v=>change('marketing',v)} sub="Volitelné. Uloží se pouze preference; zprávy se neodesílají."/></>}
      <View style={{marginTop:22}}><AButton title={step===7?'Vytvořit můj Zenvault':'Pokračovat'} loading={busy} onPress={next}/></View>
     </View>}
     {busy&&<View style={{marginTop:16}}><Text accessibilityLiveRegion="polite" style={[a.hint,{textAlign:'center'}]}>{progress?'Zabezpečení místního účtu · '+progress+' %':'Připravuji místní účet…'}</Text><View accessibilityRole="progressbar" accessibilityLabel="Průběh zabezpečení účtu" accessibilityValue={{min:0,max:100,now:progress}} style={{height:5,backgroundColor:'#D9E7F4',borderRadius:4,marginTop:12,overflow:'hidden'}}><View style={{height:5,width:progress+'%',backgroundColor:blue}}/></View><Pressable accessibilityRole="button" accessibilityLabel="Zrušit pokus" onPress={()=>operation.current?.cancel()} style={{padding:18,alignItems:'center'}}><Text style={{fontSize:13,fontWeight:'600',color:blue}}>Zrušit pokus</Text></Pressable></View>}
     {!!error&&<View accessibilityRole="alert" accessibilityLiveRegion="polite" style={{padding:16,borderRadius:18,backgroundColor:'#FFF0F1',borderWidth:1,borderColor:'#F4CDCF',marginTop:15}}><Text style={{color:'#A23346',fontSize:13,lineHeight:20}}>{error}</Text></View>}
    </Enter>
   </ScrollView>
  </KeyboardAvoidingView>
  <Modal visible={!!info} transparent animationType={reduced?'none':'fade'} onRequestClose={()=>Q(null)}><View style={{flex:1,backgroundColor:'#07152699',justifyContent:'center',padding:24}}><View style={{padding:24,borderRadius:29,backgroundColor:'#F5F9FF',maxHeight:'85%',width:'100%',maxWidth:490,alignSelf:'center'}}><ScrollView><Text style={{fontSize:24,color:ink,fontWeight:'700',marginBottom:15}}>{info==='password'?'Obnovení přístupu':'Tvůj místní účet'}</Text><Text style={{color:muted,fontSize:14,lineHeight:23}}>{info==='password'?'Heslo místního účtu nelze obnovit e-mailem ani SMS, protože účty nejsou připojené k serveru. Starší profil bez hesla otevřeš přes seznam na úvodní stránce. Pokud heslo nového účtu neznáš, můžeš založit jiný místní účet; data původního účtu zůstanou zachována.':'Zenvault 4.6.1 je lokální bankovní frontend. Vytvoření profilu nezakládá smlouvu s bankou, neověřuje totožnost a neumožňuje skutečné platby.\n\nKontaktní a registrační údaje se ukládají v úložišti aplikace na tomto zařízení. Mezi zařízeními se nepřenášejí. Pro zkoušení používej testovací osobní údaje a neposílej doklady. Heslo se ukládá pouze jako odvozený hash se solí.\n\nSmazáním dat aplikace přijdeš o místní účty. Marketingový souhlas je volitelná místní preference. Bankovní služby, právní podmínky a bezpečné serverové ověření musí zajistit budoucí provozovatel.'}</Text></ScrollView><View style={{marginTop:21}}><AButton title="Rozumím" onPress={()=>Q(null)}/></View></View></View></Modal>
 </View>;
}
const a=StyleSheet.create({title:{fontSize:35,lineHeight:40,letterSpacing:-1.4,fontWeight:'700',color:ink,marginBottom:12},subtitle:{fontSize:15,lineHeight:23,color:muted,marginBottom:27},label:{fontSize:12,fontWeight:'700',color:ink,marginBottom:9},hint:{fontSize:11,lineHeight:18,color:muted,marginTop:7},select:{borderWidth:1,borderColor:'#D9E5F1',borderRadius:18,minHeight:55,paddingHorizontal:16,paddingVertical:16,flexDirection:'row',alignItems:'center'},symbol:{width:64,height:64,borderRadius:23,borderWidth:1,borderColor:'#FFFFFF',backgroundColor:'#FFFFFF9E',alignItems:'center',justifyContent:'center',marginBottom:24}});
