// Static native assets; every tier owns three unique illustrations.
export const rollingLoudLogo=require('./assets/brands/rolling-loud.png');
export default {
 'prestige-crimson-thorns':require('./assets/cards/prestige-crimson-thorns.jpg'),
 'prestige-obsidian-bloom':require('./assets/cards/prestige-obsidian-bloom.jpg'),
 'prestige-violet-spider':require('./assets/cards/prestige-violet-spider.jpg'),
 'prestige-chrome-soul':require('./assets/cards/prestige-chrome-soul.jpg'),
 'prestige-deep-night':require('./assets/cards/prestige-deep-night.jpg'),
 'max-liquid-gold':require('./assets/cards/max-liquid-gold.jpg'),
 'max-golden-current':require('./assets/cards/max-golden-current.jpg'),
 'max-holo-medusa':require('./assets/cards/max-holo-medusa.jpg'),

 'max-rose-thorns': require('./assets/cards/max-rose-thorns.jpg'),
 'max-thorn-arc': require('./assets/cards/max-thorn-arc.jpg'),
 'max-ghost-wings': require('./assets/cards/max-ghost-wings.jpg'),
 'max-kitty-riot': require('./assets/cards/max-kitty-riot.jpg'),
 'max-pink-chrome': require('./assets/cards/max-pink-chrome.jpg'),
 'max-cobalt-chrome': require('./assets/cards/max-cobalt-chrome.jpg'),
 'max-ember-blade': require('./assets/cards/max-ember-blade.jpg'),
 'max-hazard': require('./assets/cards/max-hazard.jpg'),
 'max-stellar': require('./assets/cards/max-stellar.jpg'),
 'max-pink-americana': require('./assets/cards/max-pink-americana.jpg'),
 'unlimited-redline': require('./assets/cards/unlimited-redline.jpg'),
 'unlimited-ethereal': require('./assets/cards/unlimited-ethereal.jpg'),
 'unlimited-pink-inferno': require('./assets/cards/unlimited-pink-inferno.jpg'),
 'unlimited-chrome-stars': require('./assets/cards/unlimited-chrome-stars.jpg'),

 'unlimited-superstar': require('./assets/cards/unlimited-superstar.jpg'),
 'unlimited-iconic-pink': require('./assets/cards/unlimited-iconic-pink.jpg'),
 'unlimited-iconic-blue': require('./assets/cards/unlimited-iconic-blue.jpg'),
 'unlimited-no-time': require('./assets/cards/unlimited-no-time.jpg'),
 'unlimited-star': require('./assets/cards/unlimited-star.jpg'),
 'unlimited-red-eye': require('./assets/cards/unlimited-red-eye.jpg'),
 'unlimited-spider': require('./assets/cards/unlimited-spider.jpg'),
 'unlimited-no-love': require('./assets/cards/unlimited-no-love.jpg'),

 'rolling-loud': require('./assets/cards/rolling-loud.jpg'),
 'cyan': require('./assets/cards/cyan.jpg'),
 'lime': require('./assets/cards/lime.jpg'),
 'pink': require('./assets/cards/pink.jpg'),
 'orange': require('./assets/cards/orange.jpg'),
 'gold-scarab': require('./assets/cards/gold-scarab.jpg'),
 'gold-lion': require('./assets/cards/gold-lion.jpg'),
 'platinum-wolf': require('./assets/cards/platinum-wolf.jpg'),
 'platinum-raven': require('./assets/cards/platinum-raven.jpg'),
 'platinum-serpent': require('./assets/cards/platinum-serpent.jpg'),
 'pro-koi': require('./assets/cards/pro-koi.jpg'),
 'pro-tiger': require('./assets/cards/pro-tiger.jpg'),
 'pro-kitsune': require('./assets/cards/pro-kitsune.jpg'),
 'ultra-dragon': require('./assets/cards/ultra-dragon.jpg'),
 'ultra-phoenix': require('./assets/cards/ultra-phoenix.jpg'),
 'ultra-kraken': require('./assets/cards/ultra-kraken.jpg'),
 'business-falcon': require('./assets/cards/business-falcon.jpg'),
 'business-panther': require('./assets/cards/business-panther.jpg'),
 'business-stag': require('./assets/cards/business-stag.jpg'),
 'hologram-apex': require('./assets/cards/hologram-apex.jpg'),
};
