import React from 'react';
import {View,Text,Pressable} from 'react-native';
import {CORE_TERMS,coreTerm,coreOfferAvailable} from './Membership';

const fallback={text:'#132439',muted:'#5C7188',accent:'#147BE5',button:'#147BE5',soft:'#E7F3FF',surface:'#FFFFFF',border:'#D9E5F1'};
export const corePriceText=id=>id==='annual'?'2 490 Kč / rok':'249 Kč / měsíc · minimálně 6 měsíců';
export const coreDate=value=>new Date(value).toLocaleDateString('cs-CZ',{timeZone:'Europe/Prague'});
export function CoreBadges({t=fallback}){return <View style={{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:12,marginBottom:3}}>{['NOVÉ!','Doporučeno'].map((s,i)=><View key={s} style={{backgroundColor:i?t.soft:t.button,borderRadius:8,paddingHorizontal:9,paddingVertical:6}}><Text style={{color:i?t.accent:'#FFFFFF',fontSize:10,fontWeight:'800',letterSpacing:i?0:.6}}>{s}</Text></View>)}</View>;}
export function CoreTermPicker({value='semiannual',onChange,t=fallback}){
 return <View testID="core-term-picker" style={{gap:10,marginVertical:16}}><Text style={{fontSize:13,fontWeight:'700',color:t.text}}>Tvoje varianta Core</Text>{CORE_TERMS.map(term=><Pressable key={term.id} accessibilityRole="radio" accessibilityLabel={'Core '+term.name} accessibilityState={{checked:value===term.id}} onPress={()=>onChange(term.id)} style={{padding:19,borderRadius:22,borderWidth:1.5,borderColor:value===term.id?t.accent:t.border,backgroundColor:value===term.id?t.soft:t.surface}}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={{fontSize:16,fontWeight:'700',color:t.text}}>{term.name}{value===term.id?' ✓':''}</Text>{term.id==='annual'&&<Text style={{color:t.accent,fontSize:10,fontWeight:'800'}}>UŠETŘÍŠ 498 Kč</Text>}</View><Text style={{fontSize:23,fontWeight:'800',color:t.text,marginTop:13}}>{term.id==='annual'?'2 490 Kč':'249 Kč'}<Text style={{fontSize:12,fontWeight:'400',color:t.muted}}>{term.id==='annual'?' / rok':' / měsíc'}</Text></Text><Text style={{fontSize:12,lineHeight:19,color:t.muted,marginTop:8}}>{term.id==='annual'?'Jedna roční platba předem. V přepočtu 207,50 Kč měsíčně. Minimální doba 12 měsíců.':'6 měsíčních plateb. Celkem 1 494 Kč za minimální dobu 6 měsíců.'}</Text></Pressable>)}<Text style={{fontSize:11,lineHeight:18,color:t.muted}}>{coreOfferAvailable()?'Sjednání do 1. 1. 2027 včetně (čas v ČR).':'Nové sjednání Core již není dostupné.'} Již sjednané členství zůstává aktivní. Roční úspora je vůči 12 měsíčním platbám po 249 Kč.</Text></View>;
}
export function CoreConsent({value,onChange,term='semiannual',t=fallback}){
 const c=coreTerm(term);
 return <Pressable accessibilityRole="checkbox" accessibilityLabel="Souhlasím s dobou a cenou Core" accessibilityState={{checked:!!value}} onPress={()=>onChange(!value)} style={{flexDirection:'row',alignItems:'flex-start',gap:12,paddingVertical:15,minHeight:48}}><View style={{width:23,height:23,borderRadius:8,borderWidth:1.5,borderColor:value?t.button:t.border,backgroundColor:value?t.button:t.surface,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#FFFFFF',fontWeight:'800'}}>{value?'✓':''}</Text></View><View style={{flex:1}}><Text style={{fontSize:14,fontWeight:'600',lineHeight:21,color:t.text}}>Souhlasím s dobou a cenou Core</Text><Text style={{fontSize:12,lineHeight:19,color:t.muted,marginTop:5}}>{corePriceText(term)}. {c?.months===12?'Celkem 2 490 Kč.':'Celkem 1 494 Kč.'} Tarif lze změnit po uplynutí minimální doby.</Text></View></Pressable>;
}
export function CoreContract({membership,t=fallback}){
 if(!membership)return null;
 return <View testID="core-contract" style={{padding:19,borderRadius:22,backgroundColor:t.soft,marginVertical:15}}><Text style={{color:t.text,fontSize:16,fontWeight:'700'}}>Tvoje členství Core</Text><Text style={{color:t.text,fontSize:14,fontWeight:'600',marginTop:10}}>{corePriceText(membership.term)}</Text><Text style={{color:t.muted,fontSize:12,lineHeight:21,marginTop:8}}>Sjednáno {coreDate(membership.startedAt)}{'\n'}Minimální doba do {coreDate(membership.commitmentEndsAt)}{'\n'}Konec nabídky nemění tvoje členství. Po minimální době můžeš tarif změnit; nový závazek se automaticky neobnoví.</Text></View>;
}
