import {validAccount,cleanAccount,appearance} from './SmartTransferModel';
import {removeMembership} from './AdminMembershipModel';
import {PRESTIGE_TIER,PRESTIGE_MAX_TIER,isPrestigeTier,prestigePlan,activatePrestige} from './PrestigePlans';
import {hasMaxBenefits,hasBusinessTools} from './Membership';
import {sendBankMessage,redeemBankOffer,confirmBankDocument,notificationAction,endUserTrial} from './BankMessages';
import {findMerchant,merchantById,merchantKey,merchantBlocked} from './MerchantCatalog';
import {CREDIT_DELAYS,paymentReason,creditDate} from './PaymentTiming';
import {normalizeHomeMode,HOME_MODES} from './HomeModes';
import {APP_THEMES,canUseTheme} from './ThemeCatalog';
import {PERSONAL_TIERS,maxCardLimit,defaultCardLimit,pointsMultiplier,hasPrivateBanking,hasDisposable,assertTierChange,activateCore,activateMax,MAX_TIER,ULTRA_MAX_TIER,isMax,isUnlimitedTier,canBuildCards} from './Membership';
import {builderMotifs,motifCharge,STATIC_EDGES,parseDisplayNumber} from './UnlimitedCatalog';
// All money is stored in minor units. Rates are fixed reference rates, not live prices.
export const RATES={CZK:1,EUR:25,USD:23,GBP:29};
export const CURRENCIES=Object.keys(RATES);
export const COUNTRIES=['CZ','SK','DE','AT','PL','FR','IT','ES','GB','US','JP'];
export const CASHBACK={Silver:0,Gold:.005,Platinum:.01,Core:.0125,Pro:.015,Ultra:.02,[ULTRA_MAX_TIER]:.025,Unlimited:.03,[MAX_TIER]:.05,[PRESTIGE_TIER]:.06,[PRESTIGE_MAX_TIER]:.08,Business:0,Junior:0};
export const PARTNERS=[{id:'market',name:'Zenvault Market',category:'Nákupy',icon:'bag-outline'},{id:'travel',name:'Zenvault Travel',category:'Doprava',icon:'airplane-outline'},{id:'cafe',name:'Zenvault Café',category:'Jídlo',icon:'cafe-outline'}];
export const REWARDS=[{id:'rollingLoud',name:'Zenvault × Rolling Loud',cost:1000},{id:'theme',name:'Motiv Candy Sky',cost:300},{id:'design',name:'Karta Hologram Limited',cost:500},{id:'boost',name:'+0,5 % na další nákup u partnera',cost:200},{id:'subscription',name:'Poukaz na subscription benefit',cost:1000}];
export const includedReward=(u,id)=>!u.parentId&&((id==='design'&&(u.tier==='Business'||hasMaxBenefits(u)))||(id==='theme'&&hasMaxBenefits(u)));
export const hasLimitedAccess=u=>includedReward(u,'design')||u.unlocks.includes('design');
export const rewardCost=(u,reward)=>includedReward(u,reward.id)?0:reward.cost;
export const WIDGETS=['Balance','Spending','Vaults','Investments','Rewards','Cards','Subscriptions'];
export const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,9);
export const parsePoints=value=>{const text=String(value??'').trim().replace(/\s/g,'');const n=Number(text);return /^\d+$/.test(text)&&Number.isSafeInteger(n)&&n>=0?n:NaN;};
export const cents=s=>{const v=String(s).trim().replace(/\s/g,'').replace(',','.');const n=Math.round(Number(v)*100);return /^\d+(\.\d{1,2})?$/.test(v)&&Number.isSafeInteger(n)?n:NaN;};
export const fmt=(n,c='CZK')=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:c,maximumFractionDigits:2}).format(n/100);
export const isoDay=(d=new Date())=>{const v=new Date(d);return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`;};
export function validDay(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return false;const d=new Date(s+'T12:00:00');return Number.isFinite(+d)&&isoDay(d)===s;}
export function nextDay(s,freq,anchor){const d=new Date(s+'T12:00:00');if(freq==='weekly')d.setDate(d.getDate()+7);else{const day=anchor||d.getDate();d.setDate(1);d.setMonth(d.getMonth()+1);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));}return isoDay(d);}
const check=(v,msg)=>{if(!v)throw Error(msg);};
const positive=n=>check(Number.isSafeInteger(n)&&n>0,'Zadej kladnou částku na nejvýše dvě desetinná místa.');
const cur=c=>check(CURRENCIES.includes(c),'Nepodporovaná měna.');
const debit=(u,n,c='CZK')=>{positive(n);cur(c);check(u.balances[c]>=n,'Nedostatek prostředků.');u.balances[c]-=n;};
const credit=(u,n,c='CZK')=>{positive(n);cur(c);check(Number.isSafeInteger(u.balances[c]+n),'Částka překračuje limit.');u.balances[c]+=n;};
const record=(u,name,value,currency,kind,category,extra={},date=new Date().toISOString())=>{const x={id:makeId(),name,value,currency,kind,category,date,...extra};u.transactions.unshift(x);return x;};
export function normalizeUser(u){return {...u,homeMode:normalizeHomeMode(u.homeMode),balances:{CZK:0,EUR:0,USD:0,GBP:0,...u.balances},cards:(u.cards||[]).map(c=>({atm:true,foreign:true,countries:[],credentialVersion:1,network:'Mastercard',...c})),goals:u.goals||[],transactions:u.transactions||[],pendingTransfers:u.pendingTransfers||[],notifications:u.notifications||[],bankMessages:u.bankMessages||[],documents:u.documents||[],trialHistory:u.trialHistory||[],requests:u.requests||[],plans:u.plans||[],planLog:u.planLog||[],points:u.points||0,pointsLog:u.pointsLog||[],cashbackTotal:u.cashbackTotal||0,unlocks:u.unlocks||[],boost:u.boost||0,subscriptions:u.subscriptions||[],blockedMerchants:u.blockedMerchants||[],contacts:u.contacts||[],splits:u.splits||[],serviceRequests:u.serviceRequests||[],expenses:u.expenses||[],investments:u.investments||[],widgets:[...(u.widgets||[]).filter(w=>WIDGETS.includes(w.id)),...WIDGETS.filter(id=>!(u.widgets||[]).some(w=>w.id===id)).map(id=>({id,visible:true}))],security:{autoLock:false,biometric:false,pinConfigured:false,phrase:'',trusted:false,history:[],...u.security},travel:{active:false,country:'GB',currency:'GBP',...u.travel},operations:u.operations||[]};}
export function migrate(d){check(d&&Array.isArray(d.users)&&d.users.length,'Úložiště neobsahuje platný profil.');return {...d,version:2,featuresVersion:4,active:d.users.some(u=>u.id===d.active)?d.active:d.users[0].id,users:d.users.map(normalizeUser),installationId:d.installationId||makeId()};}
export function isExpense(x){return x.value<0&&!['Směna','Spoření','Administrace','Junior převod'].includes(x.category)&&!['exchange','vault','internal','cashback'].includes(x.kind);}
export function monthStats(u,offset=0,now=new Date()){const start=new Date(now.getFullYear(),now.getMonth()+offset,1),end=new Date(now.getFullYear(),now.getMonth()+offset+1,1);const items=u.transactions.filter(x=>new Date(x.date)>=start&&new Date(x.date)<end);const categories={};let income=0,expense=0;for(const x of items){const n=Math.round(Math.abs(x.value)*(RATES[x.currency]||1));if(isExpense(x)){expense+=n;categories[x.category]=(categories[x.category]||0)+n;}if(x.value>0&&!['Směna','Spoření','Administrace','Junior převod'].includes(x.category)&&!['internal','cashback','exchange','vault'].includes(x.kind))income+=n;}return {items,income,expense,categories};}
export function health(u){const now=monthStats(u),prev=monthStats(u,-1);const n=u.transactions.filter(isExpense).length;const reserve=Object.entries(u.balances).reduce((a,[c,v])=>a+v*RATES[c],0)+u.goals.reduce((a,g)=>a+g.saved,0);if(n<5||!prev.expense)return {score:null,reserve,reason:'Potřebujeme alespoň 5 výdajů a výdaje z minulého měsíce.'};const months=reserve/prev.expense;const savings=u.goals.reduce((a,g)=>a+g.saved,0);const factors=[{name:'Rezerva vůči minulému měsíci',points:Math.round(Math.min(1,months/3)*500),max:500},{name:'Dodržení měsíčního rozpočtu',points:Math.round(Math.max(0,1-now.expense/(u.budget||1))*300),max:300},{name:'Podíl peněz ve Vaults',points:Math.round(Math.min(1,savings/Math.max(1,reserve)/.2)*200),max:200}];return {score:factors.reduce((a,f)=>a+f.points,0),factors,reserve,months};}
function transfer(u,a,date,d){positive(a.amount);cur(a.currency);check(a.name?.trim(),'Vyplň příjemce.');const account=cleanAccount(a.account);const target=a.target&&d?.users.find(x=>x.id===a.target);if(a.target)check(target&&target.id!==u.id,'Místní příjemce není dostupný.');else check(validAccount(account),'Vyplň platné číslo účtu nebo IBAN včetně kontrolních číslic.');let request;if(a.requestId){request=target?.requests.find(r=>r.id===a.requestId);if(target)check(request&&request.status!=='paid'&&request.status!=='cancelled'&&request.amount===a.amount&&request.currency===a.currency,'Žádost již není platná nebo se změnila.');}
 debit(u,a.amount,a.currency);if(target)credit(target,a.amount,a.currency);const extra={account,target:a.target||null,...appearance(a),reference:a.op||makeId(),requestId:a.requestId||null};record(u,target?.name||a.name.trim(),-a.amount,a.currency,'transfer',a.category||'Převod',extra,date);if(target){record(target,u.name,a.amount,a.currency,'transfer','Převod',{...extra,target:u.id},date);target.notifications.unshift({id:makeId(),title:u.name+' posílá '+fmt(a.amount,a.currency),date});if(request){request.status='paid';request.paidAt=date;}}
 if(!u.contacts.some(c=>a.target?c.target===a.target:c.account===account))u.contacts.push({id:makeId(),name:target?.name||a.name.trim(),account,target:a.target||null});}
function vaultMove(u,a,date){const g=u.goals.find(g=>g.id===a.id);check(g,'Vault neexistuje.');positive(a.amount);if(a.withdraw){check(g.saved>=a.amount,'Ve Vaultu není dost peněz.');credit(u,a.amount);g.saved-=a.amount;}else{check(Number.isSafeInteger(g.saved+a.amount),'Limit Vaultu.');debit(u,a.amount);g.saved+=a.amount;}record(u,g.name,a.withdraw?a.amount:-a.amount,'CZK','vault','Spoření',{},date);}
function internal(d,u,a,date){const target=d.users.find(x=>x.id===a.target&&x.parentId===u.id);check(target,'Junior účet nepatří tomuto rodiči.');debit(u,a.amount);credit(target,a.amount);const ref=makeId();record(u,'Kapesné: '+target.name,-a.amount,'CZK','internal','Junior převod',{reference:ref},date);record(target,'Kapesné od '+u.name,a.amount,'CZK','internal','Junior převod',{reference:ref},date);}
function cardPay(u,a,date){const card=u.cards.find(c=>c.id===a.card);check(card&&!card.frozen,'Karta je zmrazená nebo neexistuje.');positive(a.amount);cur(a.currency);const channel=a.channel||'online';check(['online','atm','contactless'].includes(channel),'Neplatný druh platby.');check(card[channel]!==false,'Tento typ platby je na kartě vypnutý.');check(COUNTRIES.includes(a.country),'Vyber zemi platby.');check(a.country==='CZ'||card.foreign!==false,'Zahraniční platby jsou vypnuté.');check(!card.countries?.length||card.countries.includes(a.country),'Země není pro kartu povolená.');check(!merchantBlocked(u.blockedMerchants,a.merchant),'Obchodník je zablokovaný.');check(a.merchant?.trim(),'Vyplň obchodníka.');if(card.disposable){check(hasDisposable(u),'Jednorázová karta vyžaduje Pro, Ultra, Ultra MAX, Unlimited ∞ nebo Unlimited MAX.');check(channel==='online','Jednorázová karta je pouze pro online platby.');}
 const cz=Math.round(a.amount*RATES[a.currency]);const day=isoDay(date);const spent=u.transactions.filter(x=>x.kind==='card'&&x.cardId===card.id&&isoDay(x.date)===day).reduce((n,x)=>n+Math.round(-x.value*RATES[x.currency]),0);check(spent+cz<=Math.min(card.limit,maxCardLimit(u)),'Překročen denní limit karty.');if(u.parentId){const all=u.transactions.filter(x=>x.kind==='card'&&isoDay(x.date)===day).reduce((n,x)=>n+Math.round(-x.value*RATES[x.currency]),0);check(all+cz<=(u.juniorLimit||0),'Překročen rodičovský limit.');}
 const merchant=findMerchant(a.merchant);if(a.merchantId)check(merchantById(a.merchantId)&&merchant?.id===a.merchantId,'Šablona neodpovídá obchodníkovi. Vyber ji znovu.');const merchantName=merchant?.name||a.merchant.trim();
 debit(u,a.amount,a.currency);const p=PARTNERS.find(p=>p.name.toLowerCase()===a.merchant.trim().toLowerCase());const x=record(u,merchantName,-a.amount,a.currency,'card',p?.category||a.category||merchant?.category||'Nákupy',{cardId:card.id,channel,country:a.country,cardLast:card.last,...(merchant?{merchantId:merchant.id,merchantSnapshot:{id:merchant.id,name:merchant.name,category:merchant.category}}:{})},date);
 if(channel!=='atm'&&!u.parentId){const points=Math.floor(cz/10000)*pointsMultiplier(u);if(points){check(Number.isSafeInteger(u.points+points),'Zůstatek bodů by překročil limit. Nejprve uprav počet bodů.');u.points+=points;u.pointsLog.unshift({id:makeId(),value:points,name:merchantName,reference:x.id,date});}const rate=p?(CASHBACK[u.tier]||0)+u.boost:0;const cb=Math.round(cz*rate);if(cb){credit(u,cb);u.cashbackTotal+=cb;record(u,'Cashback · '+a.merchant,cb,'CZK','cashback','Odměny',{reference:x.id},date);}if(p&&u.boost)u.boost=0;}
 if(card.disposable){card.credentialVersion++;card.last=String((Number(card.last)+1379)%10000).padStart(4,'0');card.securityToken=makeId();}
}
function runPlan(d,u,p,now){const date=now.toISOString();if(p.kind==='transfer')transfer(u,p.data,date,d);else if(p.kind==='vault')vaultMove(u,p.data,date);else if(p.kind==='junior')internal(d,u,p.data,date);else if(p.kind==='subscription'){const sub=u.subscriptions.find(s=>s.id===p.data.id);check(sub,'Předplatné nenalezeno.');cardPay(u,{card:sub.card,merchant:sub.name,amount:sub.amount,currency:sub.currency,country:'CZ',channel:'online',category:'Předplatné'},date);}else throw Error('Neplatný plán.');}
function settleAdminTransfers(d,now){for(const u of d.users){const remaining=[];for(const x of [...u.pendingTransfers].sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt))){if(new Date(x.dueAt)>now){remaining.push(x);continue;}const balance=u.balances[x.currency]+x.value;if(balance<0){x.status='waitingFunds';remaining.push(x);continue;}if(!Number.isSafeInteger(balance)){x.status='blocked';remaining.push(x);continue;}u.balances[x.currency]=balance;u.transactions.unshift({...x,status:'posted',date:now.toISOString(),createdAt:x.date,settledAt:now.toISOString()});u.notifications.unshift({id:makeId(),title:'Platba '+x.name+' byla zaúčtována.',date:now.toISOString()});}u.pendingTransfers=remaining;}return d;}
function clampEntitlements(u){
 if(!canUseTheme(u,APP_THEMES.find(m=>m.id===u.appThemeId)))u.appThemeId='sky';
 u.cards.forEach(c=>c.limit=Math.min(c.limit||defaultCardLimit(u),maxCardLimit(u)));
}
function expireTrials(d,now){for(const u of d.users){if(u.planTrial&&+new Date(u.planTrial.endsAt)<=+now){endUserTrial(u,now);clampEntitlements(u);}}return d;}
export function processDue(input,now=new Date()){let d=expireTrials(JSON.parse(JSON.stringify(migrate(input))),now);settleAdminTransfers(d,now);const day=isoDay(now);for(const user of [...d.users]){for(const plan of [...user.plans]){if(!plan.active||plan.next>day)continue;let u=d.users.find(x=>x.id===user.id),p=u.plans.find(x=>x.id===plan.id);if(p.lastAttempt===day&&p.status==='failed')continue;let steps=0;while(p.active&&p.next<=day&&steps++<36){const due=p.next;const draft=JSON.parse(JSON.stringify(d));const du=draft.users.find(x=>x.id===u.id),dp=du.plans.find(x=>x.id===p.id);try{runPlan(draft,du,dp,now);dp.status='paid';delete dp.error;dp.lastAttempt=day;du.planLog.unshift({id:makeId(),plan:p.id,name:p.name,due,status:'paid',date:now.toISOString()});if(p.frequency==='once')dp.active=false;else dp.next=nextDay(p.next,p.frequency,p.anchor);d=draft;}catch(e){p.status='failed';p.lastAttempt=day;p.error=e.message;u.planLog.unshift({id:makeId(),plan:p.id,name:p.name,due,status:'failed',error:e.message,date:now.toISOString()});break;}u=d.users.find(x=>x.id===user.id);p=u.plans.find(x=>x.id===plan.id);}}}return d;}
export function act(input,userId,a,now=new Date()){const d=expireTrials(JSON.parse(JSON.stringify(migrate(input))),now);const u=d.users.find(x=>x.id===userId);check(u,'Profil nenalezen.');if(a.op&&u.operations.includes(a.op))return input.users.some(x=>x.planTrial&&+new Date(x.planTrial.endsAt)<=+now)?d:input;const date=now.toISOString();
 switch(a.type){
 case 'adminMembershipRemove':{const target=removeMembership(d,u,a,now,makeId);clampEntitlements(target);break;}
 case 'equityInterest':{check(isPrestigeTier(u.tier)&&!u.parentId&&!u.planTrial,'Equity Circle vyžaduje běžné členství Prestige.');if(!u.serviceRequests.some(r=>r.kind==='Equity Circle'&&r.plan===u.tier))u.serviceRequests.unshift({id:makeId(),kind:'Equity Circle',plan:u.tier,message:'Nezávazný zájem o navrhovaný podílový program až '+prestigePlan(u.tier).equity+'. Nejde o přidělené akcie.',date,status:'Uloženo',priority:u.tier});break;}
 case 'bankMessage':sendBankMessage(d,u,a,now,makeId);break;
 case 'bankOffer':redeemBankOffer(u,a,now);break;
 case 'bankDocument':confirmBankDocument(u,a,now);break;
 case 'inboxRead':case 'inboxReadAll':case 'inboxArchive':notificationAction(u,a,now);break;
 case 'trialCancel':check(u.planTrial,'Nemáš aktivní zkušební období.');endUserTrial(u,now,'cancelled');clampEntitlements(u);break;
 case 'adminTransaction':{check(d.mode==='Administrátor','Vytvoření transakce vyžaduje režim Administrátor.');const target=d.users.find(x=>x.id===a.target);check(target,'Klient nebyl nalezen.');positive(a.amount);cur(a.currency);check(a.name?.trim(),'Vyplň název transakce.');check(['Příchozí','Odchozí'].includes(a.direction),'Zvol směr platby.');check(CREDIT_DELAYS.some(x=>x.days===a.delayDays),'Neplatná doba připsání.');if(a.delayDays)check(paymentReason(a.reason),'Zvol důvod odložení platby.');const value=a.direction==='Odchozí'?-a.amount:a.amount;const item={id:makeId(),name:a.name.trim(),value,currency:a.currency,category:a.category||'Ostatní',kind:'admin',admin:true,note:a.note||'',date,delayDays:a.delayDays,dueAt:creditDate(a.delayDays,now),status:a.delayDays?'pending':'posted',reason:a.delayDays?a.reason:null};if(a.delayDays){target.pendingTransfers.unshift(item);}else{const balance=target.balances[a.currency]+value;check(Number.isSafeInteger(balance)&&balance>=0,'Nedostatek prostředků nebo překročený limit zůstatku.');target.balances[a.currency]=balance;target.transactions.unshift({...item,settledAt:date});}target.notifications.unshift({id:makeId(),title:a.delayDays?'Platba '+item.name+' čeká na připsání.':'Platba '+item.name+' byla zaúčtována.',date});break;}
 case 'membership':{check(!u.parentId,'Tarif Junior účtu spravuje rodič.');check(PERSONAL_TIERS.includes(a.tier),'Neplatný osobní tarif.');assertTierChange(u,a.tier,now);if(u.planTrial)endUserTrial(u,now,'converted');if(a.tier==='Core')Object.assign(u,activateCore(u,a.coreTerm,a.coreConsent,now));else if(a.tier===MAX_TIER)Object.assign(u,activateMax(u,now));else if(isPrestigeTier(a.tier))Object.assign(u,activatePrestige(u,a.tier,now));else u.tier=a.tier;if(!canUseTheme(u,APP_THEMES.find(m=>m.id===u.appThemeId)))u.appThemeId='sky';u.cards.forEach(c=>c.limit=Math.min(c.limit||defaultCardLimit(u),maxCardLimit(u)));break;}
 case 'buildCard':{
  const existing=a.id?u.cards.find(c=>c.id===a.id):null;
  if(a.id)check(existing&&isUnlimitedTier(existing.tier)&&!existing.limited&&!existing.edition&&!existing.disposable,'Tuto kartu nelze upravit v Card Builderu.');
  const tier=existing?.tier||a.tier||u.tier;
  check(canBuildCards(u,tier),'Tento Card Builder vyžaduje aktivní '+(isUnlimitedTier(tier)?'Zenvault '+tier:'Zenvault Unlimited')+'.');
  const motif=builderMotifs(tier).find(m=>m.id===a.motif);check(motif,'Vyber motiv dostupný pro tuto kartu.');
  check(['hologram','static'].includes(a.edge),'Vyber Hologram nebo Static.');check(STATIC_EDGES.some(e=>e.color===a.color),'Vyber platnou barvu okraje.');
  const number=parseDisplayNumber(a.displayNumber);check(number,'Zobrazené číslo musí mít přesně 16 číslic.');
  if(!existing){check(['Virtuální','Fyzická'].includes(a.cardType),'Vyber typ karty.');check(['Mastercard','Visa'].includes(a.network),'Vyber Mastercard nebo Visa.');}
  const layout=a.layout||existing?.builder?.layout||motif.layout||(motif.fullBleed?'full':'framed');check(['full','framed','fit'].includes(layout),'Vyber platnou kompozici motivu.');
  const price=motifCharge(existing,motif);if(price){check(hasMaxBenefits(u),'Art Editions vyžadují Unlimited MAX nebo Prestige.');check(a.purchaseConsent===true&&a.quotedPrice===price,'Potvrď jednorázovou cenu 899 Kč za tento design na této kartě.');debit(u,price);}
  const cardId=existing?.id||makeId();
  const changes={builder:{motif:a.motif,edge:a.edge,color:a.color,layout},displayNumber:number,last:number.slice(-4),updatedAt:date};
  if(price){const receipt=record(u,'MAX Art Edition · '+motif.name,-price,'CZK','cardPurchase','Karty',{cardId,motifId:motif.id},date);changes.artPurchases=[...(existing?.artPurchases||[]),{motifId:motif.id,amount:price,currency:'CZK',date,reference:receipt.id}];}
  if(existing)Object.assign(existing,changes);else u.cards.push({id:cardId,type:a.cardType,network:a.network,tier,design:0,limit:defaultCardLimit(u),frozen:false,online:true,atm:true,foreign:true,contactless:true,countries:[],...changes});break;
 }
 case 'appTheme':{const theme=APP_THEMES.find(m=>m.id===a.id);check(theme,'Motiv neexistuje.');check(canUseTheme(u,theme),theme.exclusive?'Tento motiv je součástí Unlimited a Prestige plánů.':'Candy Sky odemkneš za 300 bodů v Rewards; s Unlimited MAX a Prestige je v ceně.');u.appThemeId=theme.id;u.rewardTheme=false;break;}
 case 'adminPoints':{check(d.mode==='Administrátor','Úprava bodů vyžaduje režim Administrátor.');const target=d.users.find(x=>x.id===a.target);check(target,'Klient nebyl nalezen.');check(Number.isSafeInteger(a.points)&&a.points>=0,'Zadej nezáporný celý počet bodů.');const before=target.points;check(Number.isSafeInteger(before)&&before>=0,'Neplatný původní zůstatek bodů.');if(before!==a.points){target.points=a.points;target.pointsLog.unshift({id:makeId(),value:a.points-before,name:'Úprava bodů administrátorem',before,after:a.points,admin:true,actor:u.id,note:String(a.note||'').trim(),date});}break;}
 case 'transfer': transfer(u,a,date,d);break;
 case 'exchange': {cur(a.from);cur(a.to);check(a.from!==a.to,'Vyber odlišné měny.');const n=Math.round(a.amount*RATES[a.from]/RATES[a.to]);positive(n);debit(u,a.amount,a.from);credit(u,n,a.to);record(u,'Směna do '+a.to,-a.amount,a.from,'exchange','Směna',{},date);record(u,'Směna z '+a.from,n,a.to,'exchange','Směna',{},date);break;}
 case 'cardPay': cardPay(u,a,date);break;
 case 'vaultSave': {positive(a.target);check(a.name?.trim(),'Vyplň název.');if(a.id){const g=u.goals.find(x=>x.id===a.id);check(g,'Vault neexistuje.');Object.assign(g,{name:a.name,target:a.target,icon:a.icon,color:a.color});}else u.goals.push({id:makeId(),name:a.name,target:a.target,saved:0,icon:a.icon||'sparkles-outline',color:a.color||'#209ACB'});break;}
 case 'vaultMove':vaultMove(u,a,date);break;
 case 'plan':{check(validDay(a.next)&&a.next>=isoDay(now),'Vyber dnešek nebo budoucí datum ve formátu RRRR-MM-DD.');check(['once','weekly','monthly'].includes(a.frequency),'Neplatná frekvence.');check(['transfer','vault','junior'].includes(a.kind),'Neplatný plán.');positive(a.data.amount);if(a.kind==='vault')check(u.goals.some(g=>g.id===a.data.id),'Vyber Vault.');if(a.kind==='junior')check(d.users.some(x=>x.id===a.data.target&&x.parentId===u.id),'Vyber vlastní Junior účet.');if(a.kind==='transfer'){const copy=JSON.parse(JSON.stringify(u));copy.balances[a.data.currency]=a.data.amount;const draft=JSON.parse(JSON.stringify(d));draft.users=draft.users.map(x=>x.id===copy.id?copy:x);transfer(copy,a.data,date,draft);}const p={id:a.id||makeId(),name:a.name||'Pravidelná platba',kind:a.kind,data:a.data,next:a.next,anchor:Number(a.next.slice(-2)),frequency:a.frequency,active:true,status:'scheduled'};if(a.id){const i=u.plans.findIndex(x=>x.id===a.id);check(i>=0,'Plán nenalezen.');u.plans[i]=p;}else u.plans.push(p);break;}
 case 'planCancel':{const p=u.plans.find(x=>x.id===a.id);check(p,'Plán nenalezen.');p.active=false;p.status='cancelled';break;}
 case 'redeem':{const r=REWARDS.find(x=>x.id===a.id);check(r,'Odměna nenalezena.');check(!hasMaxBenefits(u)||!includedReward(u,r.id),'Tato odměna je již součástí tvého plánu.');const cost=rewardCost(u,r);check(u.points>=cost,'Nemáš dost bodů.');check(!u.unlocks.includes(a.id),'Tato odměna už je odemčená.');check(a.id!=='boost'||!u.boost,'Boost už čeká na použití.');u.points-=cost;if(cost)u.pointsLog.unshift({id:makeId(),value:-cost,name:r.name,date});if(a.id==='boost')u.boost=.005;else u.unlocks.push(a.id);break;}
 case 'disposable':check(hasDisposable(u),'Jednorázová karta je pro Pro / Ultra / Ultra MAX / Unlimited ∞ / Unlimited MAX.');u.cards.push({id:makeId(),type:'Virtuální',network:'Mastercard',tier:u.tier,design:2,last:'1000',credentialVersion:1,securityToken:makeId(),disposable:true,frozen:false,online:true,contactless:false,atm:false,foreign:true,countries:[],limit:isUnlimitedTier(u.tier)||u.tier===ULTRA_MAX_TIER?defaultCardLimit(u):1000000});break;
 case 'controls':{const c=u.cards.find(x=>x.id===a.id);check(c,'Karta nenalezena.');const v=a.values;if(v.limit!==undefined){positive(v.limit);check(v.limit<=maxCardLimit(u),'Limit překračuje maximum tvého plánu.');if(u.parentId)check(v.limit<=(u.juniorLimit||0),'Limit určuje rodič.');}if(v.countries)check(v.countries.every(x=>COUNTRIES.includes(x)),'Neplatná země.');for(const k of ['frozen','online','atm','foreign','contactless','limit','countries'])if(v[k]!==undefined)c[k]=v[k];break;}
 case 'freezeAll':u.cards.forEach(c=>c.frozen=true);break;
 case 'block':{const n=merchantKey(a.name);check(n,'Zadej obchodníka.');u.blockedMerchants=a.blocked?[...new Set([...u.blockedMerchants,n])]:u.blockedMerchants.filter(x=>merchantKey(x)!==n);break;}
 case 'subscription':{positive(a.amount);cur(a.currency);check(a.name?.trim()&&validDay(a.next),'Vyplň službu a platné datum.');check(u.cards.some(c=>c.id===a.card),'Vyber kartu.');const id=a.id||makeId();const sub={id,name:a.name,amount:a.amount,currency:a.currency,next:a.next,card:a.card,frequency:a.frequency||'monthly'};u.subscriptions=u.subscriptions.filter(s=>s.id!==id).concat(sub);u.plans=u.plans.filter(p=>!(p.kind==='subscription'&&p.data.id===id));if(a.auto)u.plans.push({id:makeId(),kind:'subscription',data:{id},name:a.name,next:a.next,anchor:Number(a.next.slice(-2)),frequency:sub.frequency,active:true,status:'scheduled'});break;}
 case 'subscriptionDelete':u.subscriptions=u.subscriptions.filter(s=>s.id!==a.id);u.plans=u.plans.filter(p=>!(p.kind==='subscription'&&p.data.id===a.id));break;
 case 'split':{positive(a.amount);cur(a.currency||'CZK');const people=a.people.split(',').map(s=>s.trim()).filter(Boolean);check(people.length>=2&&people.length<=20,'Zadej 2–20 účastníků oddělených čárkou.');const base=Math.floor(a.amount/people.length);check(base>0,'Částka je příliš malá.');u.splits.unshift({id:makeId(),name:a.name||'Společný účet',...appearance(a),date,amount:a.amount,currency:a.currency||'CZK',parts:people.map((name,i)=>({id:makeId(),name,amount:base+(i<a.amount%people.length?1:0),paid:false}))});break;}
 case 'splitPaid':{const sp=u.splits.find(s=>s.id===a.id),part=sp?.parts.find(x=>x.id===a.part);check(part,'Podíl nenalezen.');part.paid=!part.paid;break;}
 case 'request':positive(a.amount);cur(a.currency);check(!a.iban||validAccount(a.iban),'Neplatný účet nebo IBAN.');u.requests.unshift({id:makeId(),ownerId:u.id,status:'open',amount:a.amount,currency:a.currency,...appearance(a),date,iban:cleanAccount(a.iban)});break;
 case 'travel':check(COUNTRIES.includes(a.country)&&CURRENCIES.includes(a.currency),'Neplatná destinace.');u.travel={active:a.active,country:a.country,currency:a.currency};break;
 case 'security':u.security={...u.security,...a.values};break;
 case 'serviceRequest':check(hasPrivateBanking(u),'Služba vyžaduje Ultra, Ultra MAX, Unlimited nebo Prestige členství.');check(a.message?.trim(),'Popiš svůj požadavek.');u.serviceRequests.unshift({id:makeId(),kind:a.kind,message:a.message,date,status:'Uloženo',priority:isPrestigeTier(u.tier)?u.tier:isMax(u)?'MAX':u.tier==='Unlimited'?'Unlimited':u.tier===ULTRA_MAX_TIER?'Ultra MAX':'Ultra'});break;
 case 'employee':check(hasBusinessTools(u),'Firemní karty jsou pro Business a Prestige.');check(a.name?.trim(),'Vyplň zaměstnance.');positive(a.limit);check(a.limit<=maxCardLimit(u),'Limit zaměstnanecké karty přesahuje maximum tarifu.');u.cards.push({id:makeId(),type:'Fyzická',network:'Mastercard',tier:'Business',design:0,last:'2000',owner:a.name,limit:a.limit,frozen:false,online:true,atm:true,foreign:true,contactless:true,countries:[]});break;
 case 'expense':{check(hasBusinessTools(u),'Výdaje jsou pro Business a Prestige.');positive(a.amount);cur(a.currency);check(a.name?.trim(),'Vyplň popis.');u.expenses.unshift({id:makeId(),name:a.name,amount:a.amount,currency:a.currency,employee:a.employee||'',status:'K posouzení',date});break;}
 case 'expenseStatus':{check(hasBusinessTools(u),'Pouze Business a Prestige.');const e=u.expenses.find(e=>e.id===a.id);check(e,'Výdaj nenalezen.');e.status=a.status;break;}
 case 'businessActivate':{check(d.mode==='Administrátor','Vyžaduje režim Administrátor.');const target=d.users.find(x=>x.id===a.target);check(target&&!target.parentId,'Vyber dospělý profil.');assertTierChange(target,'Business',now);if(target.planTrial)endUserTrial(target,now,'converted');target.tier='Business';clampEntitlements(target);break;}
 case 'juniorCreate':{check(!u.parentId,'Junior nemůže vytvářet další účty.');check(a.name?.trim(),'Vyplň jméno.');positive(a.limit);const id=makeId();d.users.push(normalizeUser({id,name:a.name,tier:'Silver',parentId:u.id,juniorLimit:a.limit,balances:{CZK:0,EUR:0,USD:0,GBP:0},cards:[{id:makeId(),type:'Virtuální',network:'Mastercard',tier:'Silver',design:0,last:'3000',limit:a.limit,frozen:false,online:true,atm:false,foreign:false,contactless:true}],budget:a.limit*30}));break;}
 case 'juniorTransfer':internal(d,u,a,date);break;
 case 'juniorLimit':{const child=d.users.find(x=>x.id===a.target&&x.parentId===u.id);check(child,'Junior účet nenalezen.');positive(a.limit);child.juniorLimit=a.limit;child.cards.forEach(c=>c.limit=Math.min(c.limit,a.limit));break;}
 case 'gallery':{check(a.tier===u.tier,'Tento design patří jinému tarifu.');check([0,1,2].includes(a.design),'Neplatný design.');check(['Virtuální','Fyzická'].includes(a.cardType),'Neplatný typ karty.');check(!a.edition||a.edition==='rollingLoud','Neznámá edice karty.');check(!(a.limited&&a.edition),'Zvol pouze jednu speciální edici.');if(a.edition==='rollingLoud')check(u.unlocks.includes('rollingLoud'),'Edici Rolling Loud odemkni za 1 000 bodů.');if(isUnlimitedTier(u.tier)&&!a.limited&&!a.edition)throw Error('Pro tuto kartu použij Card Builder.');if(a.limited)check(hasLimitedAccess(u),'Odemkni design za body nebo získej plán Business nebo Unlimited MAX.');u.cards.push({id:makeId(),type:a.cardType,network:a.network||'Mastercard',tier:a.tier,design:a.design,limited:!!a.limited,...(a.edition?{edition:a.edition}:{}),last:'4000',limit:isUnlimitedTier(u.tier)||u.tier===ULTRA_MAX_TIER?defaultCardLimit(u):1000000,frozen:false,online:true,atm:true,foreign:true,contactless:true,countries:[]});break;}
 case 'investmentSave':{check(a.name?.trim(),'Vyplň název investice.');cur(a.currency);positive(a.cost);check(Number.isSafeInteger(a.value)&&a.value>=0,'Zadej nezápornou aktuální hodnotu.');if(a.id)check(u.investments.some(x=>x.id===a.id),'Investice nenalezena.');const item={id:a.id||makeId(),name:a.name,currency:a.currency,cost:a.cost,value:a.value,date};u.investments=u.investments.filter(x=>x.id!==item.id).concat(item);break;}
 case 'investmentDelete':u.investments=u.investments.filter(x=>x.id!==a.id);break;
 case 'homeMode':check(HOME_MODES.some(m=>m.id===a.id),'Vyber platný režim přehledu.');u.homeMode=a.id;break;
 case 'widgets':check(a.widgets.length===WIDGETS.length&&WIDGETS.every(id=>a.widgets.some(w=>w.id===id)),'Neplatné widgety.');u.widgets=a.widgets;break;
 case 'rewardTheme':check(!a.enabled||canUseTheme(u,APP_THEMES.find(m=>m.id==='candy')),'Motiv není odemčený.');u.rewardTheme=a.enabled;break;
 default:throw Error('Neznámá operace.');
 }
 if(a.op)u.operations.push(a.op);return d;
}
export function askAssistant(u,q){const norm=q.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(/odloz|usetri|spor/.test(norm)){const match=norm.match(/\d[\d\s]*(?:[,.]\d{1,2})?/);const wanted=match?cents(match[0]):0;const s=monthStats(u);const obligations=u.plans.filter(p=>p.active&&p.kind==='subscription').reduce((n,p)=>{const sub=u.subscriptions.find(s=>s.id===p.data.id);return n+(sub?sub.amount*RATES[sub.currency]:0);},0);const free=Math.max(0,u.balances.CZK-Math.max(0,u.budget-s.expense)-obligations);return `Po rezervování zbytku měsíčního rozpočtu a jednoho cyklu automatických předplatných zbývá orientačně ${fmt(free)}. ${wanted?(free>=wanted?'Požadovaná částka se do této rezervy vejde.':'Požadovaná částka je nad touto rezervou.'):''} Výpočet nezná tvé budoucí příjmy ani všechny závazky.`;}
 if(/minul|mesic|jidlo|doprav|nakup|utrat/.test(norm)){const prev=/minul/.test(norm),s=monthStats(u,prev?-1:0);const cat=/jidlo/.test(norm)?'Jídlo':/doprav/.test(norm)?'Doprava':/nakup/.test(norm)?'Nákupy':null;return `${prev?'Minulý':'Tento'} měsíc eviduji ${cat?'v kategorii '+cat:'na výdajích'} ${fmt(cat?s.categories[cat]||0:s.expense)}. Cizí měny přepočítávám pevným referenčním kurzem. ${s.items.length?'':'V tomto období nejsou transakce.'}`;}
 if(/bod/.test(norm))return `Máš ${u.points} bodů a celkem ${fmt(u.cashbackTotal)} připsaného cashbacku.`;return 'Umím spočítat výdaje za tento nebo minulý měsíc, jídlo, dopravu, nákupy, body a orientační částku na odložení. Zkus: Kolik jsem minul minulý měsíc za jídlo?';}
