import {unreadCount} from './BankMessages';
import {MerchantIcon} from './MerchantUI';
import {merchantForTransaction} from './MerchantCatalog';
import React,{useMemo} from 'react';
import {homeWidgetIds} from './HomeModes';
import {transactionFeed,paymentStatus} from './PaymentTiming';
import {View,Text,Pressable,ScrollView,useWindowDimensions} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {CURRENCIES,RATES,fmt,monthStats} from './engine';
import {tierLabel} from './Membership';
import {Touch} from './Motion';

export function HomeHeader({u,ui,onAccounts,onTiers,onNotifications,notificationsEnabled=true}){
 const {t,Label,Icon}=ui;
 return <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:25,marginBottom:24}}>
  <Pressable accessibilityRole="button" accessibilityLabel="Přepnout účet" onPress={onAccounts} style={{flex:1,flexDirection:'row',gap:11,alignItems:'center'}}><LinearGradient colors={[t.theme.glow,t.soft]} style={{width:45,height:45,borderRadius:18,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#FFFFFF85'}}><Text style={{fontWeight:'800',fontSize:16,color:t.mono?'#000000':'#18314E'}}>{u.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</Text></LinearGradient><View style={{flexShrink:1}}><Label muted style={{fontSize:11,marginBottom:3}}>Vítej zpátky,</Label><Label numberOfLines={1} style={{fontSize:19,fontWeight:'700',letterSpacing:-.6}}>{u.name.split(' ')[0]} <Icon name="chevron-down" size={12}/></Label></View></Pressable>
  <Pressable accessibilityRole="button" accessibilityLabel="Členství" onPress={onTiers} style={{padding:10,borderRadius:25,backgroundColor:t.surface,marginRight:7,borderWidth:1,borderColor:t.border}}><Label style={{fontSize:10,fontWeight:'800',color:t.accent}}>{tierLabel(u.tier).toUpperCase()}</Label></Pressable>
  <Pressable accessibilityRole="button" accessibilityLabel="Oznámení" onPress={onNotifications} style={{width:43,height:43,alignItems:'center',justifyContent:'center',borderRadius:22,backgroundColor:t.surface,borderWidth:1,borderColor:t.border}}><Icon name="notifications-outline" size={21}/>{notificationsEnabled&&unreadCount(u)>0&&<View style={{position:'absolute',right:10,top:8,width:6,height:6,borderRadius:3,backgroundColor:t.accent}}/>}</Pressable>
 </View>;
}
export function PromoBubble({ui,onPress}){
 const {t,Label,Icon}=ui;
 return <View style={{borderRadius:23,shadowColor:t.theme.accent,shadowOpacity:.09,shadowRadius:16,shadowOffset:{width:0,height:6}}}><LinearGradient colors={t.featureGradient} start={{x:0,y:0}} end={{x:1,y:1}} style={{borderRadius:23,padding:14,borderWidth:1,borderColor:t.border,flexDirection:'row',alignItems:'center',gap:11}}><View style={{height:39,width:39,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:t.soft}}><Icon name="gift-outline" size={21} color={t.accent}/></View><View style={{flex:1}}><Label style={{fontSize:12,lineHeight:17,fontWeight:'700'}}>Netflix nebo HBO Max na měsíc zdarma!</Label><Pressable accessibilityRole="button" accessibilityLabel="Více informací" onPress={onPress} style={{minHeight:28,justifyContent:'center'}}><Label style={{fontSize:11,fontWeight:'700',color:t.accent}}>Více informací  ↗</Label></Pressable></View><Icon name="sparkles" size={16} color={t.accent}/></LinearGradient></View>;
}
export default function Home4({u,data,ui,go,onOpen,renderCard,currency,setCurrency,onTransaction}){
 const {t,Panel,Label,Icon,Section,Button,Row}=ui,hidden=data.hide;
 const monthKey=new Date().getFullYear()+'-'+new Date().getMonth();
 const [now,previous]=useMemo(()=>[monthStats(u),monthStats(u,-1)],[u.transactions,u.budget,monthKey]);
 const week=useMemo(()=>now.items.reduce((days,x)=>{if(x.value<0)days[new Date(x.date).getDay()]+=Math.abs(x.value)*RATES[x.currency];return days;},Array(7).fill(0)),[now]);
 const recent=useMemo(()=>transactionFeed(u).slice(0,5),[u.transactions,u.pendingTransfers]);
 const val=(n,c='CZK')=>hidden?'••••••':fmt(n,c);
 const {width}=useWindowDimensions(),balanceText=val(u.balances[currency],currency),balanceFont=Math.min(49,Math.max(18,(Math.min(width,620)-44)/(balanceText.length*.64))); 
 const actions=[['arrow-up-outline','Odeslat','transfer'],['arrow-down-outline','Vyžádat','requests'],['swap-horizontal-outline','Směnit','wallet'],['apps-outline','Více','hub']];
 const balance=()=> <View testID="balance-widget" style={{marginBottom:24}}>
  <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Label muted style={{fontSize:13}}>{u.tier==='Business'?'Firemní prostředky':'Dostupný zůstatek'}</Label><Pressable accessibilityRole="button" accessibilityLabel="Měnové účty" onPress={()=>go('wallet')} style={{flexDirection:'row',alignItems:'center',gap:5,padding:8}}><Icon name="globe-outline" size={15} color={t.muted}/><Label muted style={{fontSize:11}}>Účty</Label></Pressable></View>
  <Label numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.45} testID="home-balance-value" style={{fontSize:balanceFont,fontWeight:'700',letterSpacing:-1.6,marginTop:5,marginBottom:18}}>{balanceText}</Label>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7,paddingBottom:5}}>{CURRENCIES.map(c=><Pressable accessibilityRole="button" accessibilityLabel={'Účet '+c} key={c} onPress={()=>setCurrency(c)} style={{paddingHorizontal:13,paddingVertical:8,borderRadius:24,backgroundColor:currency===c?t.text:t.surface,borderWidth:1,borderColor:currency===c?t.text:t.border}}><Text style={{fontSize:11,fontWeight:'700',color:currency===c?t.bg:t.muted}}>{c}</Text></Pressable>)}</ScrollView>
  <View style={{flexDirection:'row',gap:9,marginTop:20}}>{actions.map(([icon,label,id],i)=><Touch key={id} accessibilityRole="button" accessibilityLabel={label} onPress={()=>go(id)} style={{flex:1,alignItems:'center',gap:9}}><View style={{height:54,width:54,backgroundColor:i===0?t.button:t.surface,borderRadius:28,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:i===0?t.button:t.border}}><Icon name={icon} size={24} color={i===0?'#FFFFFF':t.text}/></View><Label style={{fontWeight:'600',fontSize:11}}>{label}</Label></Touch>)}</View>
 </View>;
 const modules={
  Balance:balance,
  Spending:()=> <Touch accessibilityRole="button" accessibilityLabel="Zenvault Insights" onPress={()=>go('insights')}><Panel style={{padding:22}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Label style={{fontSize:13,fontWeight:'600'}}>Výdaje tento měsíc</Label><Icon name="arrow-forward-outline" size={18} color={t.muted}/></View><View style={{flexDirection:'row',alignItems:'flex-end',gap:14,marginTop:18}}><View style={{flex:1}}><Label style={{fontSize:28,fontWeight:'700',letterSpacing:-1}}>{val(now.expense)}</Label><Label muted style={{fontSize:11,lineHeight:17,marginTop:7}}>{hidden?'Přehled tvého měsíce':previous.expense?`${Math.round((now.expense/previous.expense-1)*100)} % oproti minulému měsíci`:'Tvůj finanční rytmus začíná tady.'}</Label></View><View style={{height:50,flexDirection:'row',alignItems:'flex-end',gap:4}}>{Array.from({length:7},(_,i)=>{const n=week[i];return <View key={i} style={{width:7,height:hidden?5:Math.max(5,Math.min(50,n/Math.max(1,now.expense)*90)),borderRadius:5,backgroundColor:i===6?t.accent:t.theme.glow,opacity:n?.9:.35}}/>;})}</View></View><View style={{height:4,borderRadius:3,backgroundColor:t.soft,marginTop:20,overflow:'hidden'}}><View style={{height:4,width:(hidden?0:Math.min(100,now.expense/Math.max(1,u.budget)*100))+'%',backgroundColor:t.accent,borderRadius:3}}/></View></Panel></Touch>,
  Vaults:()=> <Touch accessibilityRole="button" accessibilityLabel="Vaults / Spaces" onPress={()=>go('vaults')}><Panel style={{padding:22}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><View style={{flex:1}}><Label muted style={{fontSize:10,letterSpacing:1.6,fontWeight:'700'}}>MAKE ROOM FOR MORE</Label><Label style={{fontSize:23,fontWeight:'700',letterSpacing:-.6,marginTop:8}}>Tvoje malé velké plány.</Label><Label muted style={{fontSize:12,marginTop:10}}>{u.goals.length} Vaults · {val(u.goals.reduce((n,g)=>n+g.saved,0))}</Label></View><View style={{alignSelf:'center',width:48,height:57,borderRadius:18,backgroundColor:t.soft,alignItems:'center',justifyContent:'center',transform:[{rotate:'8deg'}]}}><Icon name="sparkles-outline" size={26} color={t.accent}/></View></View>{u.goals.slice(0,2).map(g=><View key={g.id} style={{marginTop:17}}><View style={{flexDirection:'row',justifyContent:'space-between',marginBottom:7}}><Label style={{fontSize:11,fontWeight:'600'}}>{g.name}</Label><Label muted style={{fontSize:10}}>{hidden?'•••':Math.round(g.saved/g.target*100)+' %'}</Label></View><View style={{height:4,backgroundColor:t.soft,borderRadius:8,overflow:'hidden'}}><View style={{height:4,width:(hidden?0:Math.min(100,g.saved/g.target*100))+'%',backgroundColor:t.accent}}/></View></View>)}</Panel></Touch>,
  History:()=> <View><Section title="Poslední transakce" action="Zobrazit vše" onPress={()=>onOpen('Platby')}/><Panel style={{paddingVertical:4}}>{recent.length?recent.map(x=><Row key={x.id} leading={merchantForTransaction(x)?<MerchantIcon merchant={merchantForTransaction(x)}/>:null} icon={x.value>0?'arrow-down-outline':x.category==='Předplatné'?'repeat-outline':'arrow-up-outline'} title={x.name} sub={(x.status&&x.status!=='posted'?paymentStatus(x):x.category)+' · '+new Date(x.dueAt||x.date).toLocaleDateString('cs-CZ',{day:'numeric',month:'short'})} onPress={()=>onTransaction(x)} right={<Label style={{fontSize:13,fontWeight:'700',color:x.value>0?t.positive:t.text}}>{hidden?'••••':(x.value>0?'+':'')+fmt(x.value,x.currency)}</Label>}/>):<View style={{paddingVertical:20}}><Label style={{fontWeight:'600'}}>Tady začne tvoje historie.</Label><Label muted style={{fontSize:12,lineHeight:20,marginTop:7}}>Po první platbě uvidíš poslední pohyby přímo na přehledu.</Label></View>}</Panel></View>,
  Cards:()=> <View><Section title="Tvoje karty" action="Otevřít peněženku" onPress={()=>onOpen('Karty')}/><Touch accessibilityRole="button" accessibilityLabel="Otevřít kartu" onPress={()=>onOpen('Karty')}>{u.cards[0]?renderCard(u.cards[0]):<Panel><Label muted>Přidej svou první kartu.</Label></Panel>}</Touch></View>,
  Rewards:()=> <Touch accessibilityRole="button" accessibilityLabel="Zenvault Rewards" onPress={()=>go('rewards')}><LinearGradient colors={t.featureGradient} start={{x:0,y:0}} end={{x:1,y:1}} style={{padding:23,borderRadius:28,borderWidth:1,borderColor:t.border,overflow:'hidden'}}><View style={{position:'absolute',right:-20,top:-35,width:148,height:148,borderRadius:75,borderWidth:30,borderColor:t.theme.glow+'35'}}/><View style={{flexDirection:'row',justifyContent:'space-between'}}><Label style={{fontSize:12,fontWeight:'700'}}>ZENVAULT POINTS</Label><Icon name="sparkles" color={t.accent} size={18}/></View><Label style={{fontSize:34,fontWeight:'700',letterSpacing:-1,marginTop:12}}>{hidden?'••••':u.points.toLocaleString('cs-CZ')}<Label muted style={{fontSize:13}}> bodů</Label></Label><Label muted style={{fontSize:12,marginTop:8}}>Malá odměna. Velký rozdíl.  ↗</Label></LinearGradient></Touch>,
  Investments:()=> <Touch accessibilityRole="button" accessibilityLabel="Investments" onPress={()=>go('investments')}><Panel><View style={{flexDirection:'row',alignItems:'center',gap:14}}><View style={{width:44,height:44,borderRadius:16,backgroundColor:t.soft,justifyContent:'center',alignItems:'center'}}><Icon name="trending-up-outline" color={t.accent}/></View><View style={{flex:1}}><Label style={{fontWeight:'700'}}>Tvoje portfolio</Label><Label muted style={{fontSize:11,marginTop:5}}>Ručně sledované investice</Label></View><Label style={{fontSize:14,fontWeight:'700'}}>{val(u.investments.reduce((n,x)=>n+x.value*RATES[x.currency],0))}</Label></View></Panel></Touch>,
  Subscriptions:()=> <Touch accessibilityRole="button" accessibilityLabel="Předplatná" onPress={()=>go('subscriptions')}><Panel><View style={{flexDirection:'row',alignItems:'center',gap:14}}><View style={{width:44,height:44,borderRadius:16,backgroundColor:t.soft,justifyContent:'center',alignItems:'center'}}><Icon name="repeat-outline" color={t.accent}/></View><View style={{flex:1}}><Label style={{fontWeight:'700'}}>Předplatná pod kontrolou</Label><Label muted style={{fontSize:11,marginTop:5}}>{u.subscriptions.length?u.subscriptions.length+' služeb ve tvém přehledu':'Netflix, Spotify, iCloud a další'}</Label></View><Icon name="chevron-forward" size={17} color={t.muted}/></View></Panel></Touch>,
 };
 return <>
  {u.tier==='Business'&&u.homeMode==='full'?<>{balance()}<Section title="Business overview"/><Panel><Label muted>Cashflow tento měsíc</Label><Label style={{fontSize:30,fontWeight:'700',marginVertical:12}}>{val(now.income-now.expense)}</Label><Label muted style={{lineHeight:24}}>Příjmy {val(now.income)}{'\n'}Výdaje {val(now.expense)}</Label><Button title="Business Dashboard" style={{marginTop:18}} onPress={()=>go('business')}/></Panel><View style={{height:15}}/>{modules.Cards()}</>:homeWidgetIds(u).map(id=><View key={id} testID={'home-widget-'+id} style={{marginBottom:14}}>{modules[id]?.()}</View>)}
  {(u.homeMode||'full')==='full'&&<><Section title="Tvůj Zenvault. Tvoje pravidla."/><Panel><View style={{flexDirection:'row',alignItems:'center',gap:13}}><Icon name="grid-outline" color={t.accent}/><View style={{flex:1}}><Label style={{fontWeight:'700'}}>Přehled podle tebe</Label><Label muted style={{fontSize:12,lineHeight:19,marginTop:5}}>Sestav si widgety tak, jak ti vyhovují.</Label></View></View><Button title="Upravit přehled" secondary style={{marginTop:17}} onPress={()=>go('widgets')}/></Panel></>}
  <Pressable accessibilityRole="button" accessibilityLabel="Zenvault Life" onPress={()=>go('hub')} style={{alignItems:'center',padding:26}}><Label style={{fontSize:20,fontWeight:'800',letterSpacing:-1}}>zenvault®</Label><Label muted style={{fontSize:9,letterSpacing:2.3,marginTop:5}}>MONEY. ON YOUR TERMS.</Label></Pressable>
 </>;
}
