import React,{useState} from 'react';
import {Platform,View} from 'react-native';
import * as LocalAuthentication from 'expo-local-authentication';
import * as SecureStore from 'expo-secure-store';
import * as Crypto from 'expo-crypto';
const key=id=>'zenvault.pin.'+id.replace(/[^a-zA-Z0-9._-]/g,'');
export async function biometric(){if(Platform.OS==='web')throw Error('Biometrie není ve webovém náhledu dostupná.');if(!await LocalAuthentication.hasHardwareAsync()||!await LocalAuthentication.isEnrolledAsync())throw Error('Na zařízení není dostupná nastavená biometrie.');const r=await LocalAuthentication.authenticateAsync({promptMessage:'Odemknout Zenvault',cancelLabel:'Zrušit',disableDeviceFallback:false});if(!r.success)throw Error('Ověření neproběhlo. Face ID v Expo Go na iOS není podporované; vyžaduje vlastní vývojový build.');return true;}
export async function verifyPin(id,pin){if(Platform.OS==='web')throw Error('PIN je dostupný v nativní aplikaci.');const raw=await SecureStore.getItemAsync(key(id));if(!raw)throw Error('PIN pro tento profil nebyl nastaven.');const data=JSON.parse(raw);if(data.until>Date.now())throw Error('Příliš mnoho pokusů. Zkus to za minutu.');const value=await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,data.salt+pin);if(value!==data.hash){data.tries=(data.tries||0)+1;if(data.tries>=5){data.until=Date.now()+60000;data.tries=0;}await SecureStore.setItemAsync(key(id),JSON.stringify(data));throw Error('Nesprávný PIN.');}data.tries=0;data.until=0;await SecureStore.setItemAsync(key(id),JSON.stringify(data));return true;}
export async function setPin(id,pin,old){if(Platform.OS==='web')throw Error('Bezpečné uložení PINu vyžaduje nativní aplikaci.');if(!/^\d{6}$/.test(pin))throw Error('PIN musí mít 6 číslic.');if(await SecureStore.getItemAsync(key(id)))await verifyPin(id,old);const bytes=await Crypto.getRandomBytesAsync(16);const salt=Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('');const hash=await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,salt+pin);await SecureStore.setItemAsync(key(id),JSON.stringify({salt,hash,tries:0,until:0}));}
export function LockScreen({u,ui,onUnlock}){const {Panel,Label,Button,Field,t}=ui;const [pin,S]=useState(''),[error,E]=useState(''),[working,W]=useState(false);const run=async mode=>{W(true);try{await(mode==='pin'?verifyPin(u.id,pin):biometric());onUnlock();}catch(e){E(e.message);}finally{W(false);}};return <View style={{flex:1,backgroundColor:t.bg,justifyContent:'center',padding:25}}><Panel><Label style={{fontSize:32,fontWeight:'800',marginBottom:10}}>zenvault®</Label><Label muted style={{marginBottom:24}}>Odemkni profil {u.name}</Label>{u.security.pinConfigured&&<><Field label="PIN" value={pin} onChangeText={S} keyboardType="number-pad" secureTextEntry maxLength={6}/><Button title="Odemknout PINem" disabled={working} onPress={()=>run('pin')}/></>}{u.security.biometric&&<Button title="Ověřit na zařízení" disabled={working} secondary style={{marginTop:12}} onPress={()=>run('bio')}/>}<Label muted style={{marginTop:15,lineHeight:22}}>{error||u.security.phrase||'Soukromí začíná u tebe.'}</Label></Panel></View>;}
